/**
 * Exercise name translations: English -> Spanish (Latin American)
 * Covers 1211 of 1318 exercises
 */
export const EXERCISE_NAMES_ES: Record<string, string> = {
  '3/4 sit-up': 'Abdominal 3/4',
  '45° side bend': 'Flexión lateral 45°',
  'air bike': 'Bicicleta aérea',
  'all fours squad stretch': 'Estiramiento en cuadrupedia',
  'alternate heel touchers': 'Toque alterno de talones',
  'alternate lateral pulldown': 'Jalón lateral alterno',
  'ankle circles': 'Círculos de tobillo',
  'archer pull up': 'Dominada arquero',
  'archer push up': 'Flexión de brazos arquero',
  'arm slingers hanging bent knee legs': 'Colgamiento de brazos con piernas colgando rodillas flexionadas',
  'arm slingers hanging straight legs': 'Colgamiento de brazos con piernas colgando rectas',
  'arms apart circular toe touch (male)': 'Toque circular de pies con brazos abiertos',
  'arms overhead full sit-up (male)': 'Abdominal completo con brazos arriba',
  'assisted chest dip (kneeling)': 'Fondos para pecho asistidos (arrodillado)',
  'assisted lying calves stretch': 'Estiramiento de pantorrillas acostado asistido',
  'assisted lying glutes stretch': 'Estiramiento de glúteos acostado asistido',
  'assisted lying gluteus and piriformis stretch': 'Estiramiento de glúteo y piriforme acostado asistido',
  'assisted lying leg raise with lateral throw down': 'Elevación de pierna acostado asistido con lanzamiento lateral',
  'assisted lying leg raise with throw down': 'Elevación de pierna acostado asistido con lanzamiento',
  'assisted motion russian twist': 'Giro ruso con movimiento asistido',
  'assisted parallel close grip pull-up': 'Dominada agarre cerrado paralelo asistida',
  'assisted prone hamstring': 'Isquiotibiales prono asistido',
  'assisted prone lying quads stretch': 'Estiramiento de cuádriceps prono acostado asistido',
  'assisted prone rectus femoris stretch': 'Estiramiento de recto femoral prono asistido',
  'assisted pull-up': 'Dominada asistida',
  'assisted seated pectoralis major stretch with stability ball': 'Estiramiento de pectoral mayor sentado asistido con balón',
  'assisted side lying adductor stretch': 'Estiramiento de aductores acostado lateral asistido',
  'assisted sit-up': 'Abdominal asistido',
  'assisted standing chin-up': 'Dominada agarre supino de pie asistida',
  'assisted standing pull-up': 'Dominada de pie asistida',
  'assisted triceps dip (kneeling)': 'Fondos de tríceps asistidos (arrodillado)',
  'assisted wide-grip chest dip (kneeling)': 'Fondos para pecho agarre abierto asistidos (arrodillado)',
  'astride jumps (male)': 'Saltos a horcajadas',
  'back extension on exercise ball': 'Extensión de espalda en balón de ejercicio',
  'back lever': 'Palanca posterior',
  'back pec stretch': 'Estiramiento de pecho posterior',
  'backward jump': 'Salto hacia atrás',
  'balance board': 'Tabla de equilibrio',
  'band alternating biceps curl': 'Curl alterno de bíceps con banda',
  'band alternating v-up': 'V-up alterno con banda',
  'band assisted pull-up': 'Dominada asistida con banda',
  'band assisted wheel rollerout': 'Rodamiento de rueda asistido con banda',
  'band bench press': 'Press de banca con banda',
  'band bent-over hip extension': 'Extensión de cadera inclinada con banda',
  'band bicycle crunch': 'Crunch de bicicleta con banda',
  'band close-grip pulldown': 'Jalón agarre cerrado con banda',
  'band close-grip push-up': 'Flexión de brazos agarre cerrado con banda',
  'band concentration curl': 'Curl de concentración con banda',
  'band fixed back close grip pulldown': 'Jalón agarre cerrado espalda fija con banda',
  'band fixed back underhand pulldown': 'Jalón supino espalda fija con banda',
  'band front lateral raise': 'Elevación lateral frontal con banda',
  'band front raise': 'Elevación frontal con banda',
  'band hip lift': 'Elevación de cadera con banda',
  'band horizontal pallof press': 'Press Pallof horizontal con banda',
  'band jack knife sit-up': 'Abdominal jackknife con banda',
  'band kneeling one arm pulldown': 'Jalón a un brazo arrodillado con banda',
  'band kneeling twisting crunch': 'Crunch giratorio arrodillado con banda',
  'band lying hip internal rotation': 'Rotación interna de cadera acostado con banda',
  'band lying straight leg raise': 'Elevación de pierna recta acostado con banda',
  'band one arm overhead biceps curl': 'Curl de bíceps a un brazo arriba con banda',
  'band one arm single leg split squat': 'Sentadilla dividida a una pierna a un brazo con banda',
  'band one arm standing low row': 'Remo bajo a un brazo de pie con banda',
  'band one arm twisting chest press': 'Press de pecho giratorio a un brazo con banda',
  'band one arm twisting seated row': 'Remo sentado giratorio a un brazo con banda',
  'band pull through': 'Jalón cruzado con banda',
  'band push sit-up': 'Abdominal con empuje de banda',
  'band reverse fly': 'Apertura inversa con banda',
  'band reverse wrist curl': 'Curl de muñeca inverso con banda',
  'band seated hip internal rotation': 'Rotación interna de cadera sentado con banda',
  'band seated twist': 'Giro sentado con banda',
  'band shoulder press': 'Press de hombro con banda',
  'band shrug': 'Encogimiento con banda',
  'band side triceps extension': 'Extensión de tríceps lateral con banda',
  'band single leg calf raise': 'Elevación de pantorrillas a una pierna con banda',
  'band single leg reverse calf raise': 'Elevación de pantorrillas inversa a una pierna con banda',
  'band single leg split squat': 'Sentadilla dividida a una pierna con banda',
  'band squat': 'Sentadilla con banda',
  'band squat row': 'Remo en sentadilla con banda',
  'band standing crunch': 'Crunch de pie con banda',
  'band standing rear delt row': 'Remo de deltoides posterior de pie con banda',
  'band standing twisting crunch': 'Crunch giratorio de pie con banda',
  'band step-up': 'Step-up con banda',
  'band stiff leg deadlift': 'Peso muerto con piernas rígidas con banda',
  'band straight back stiff leg deadlift': 'Peso muerto con piernas rígidas espalda recta con banda',
  'band straight leg deadlift': 'Peso muerto con piernas rectas con banda',
  'band twisting overhead press': 'Press arriba giratorio con banda',
  'band two legs calf raise - (band under both legs) v. 2': 'Elevación de pantorrillas a dos piernas con banda v. 2',
  'band underhand pulldown': 'Jalón supino con banda',
  'band v-up': 'V-up con banda',
  'band vertical pallof press': 'Press Pallof vertical con banda',
  'band wrist curl': 'Curl de muñeca con banda',
  'band y-raise': 'Elevación en Y con banda',
  'barbell alternate biceps curl': 'Curl alterno de bíceps con barra',
  'barbell bench front squat': 'Sentadilla frontal en banca con barra',
  'barbell bench press': 'Press de banca con barra',
  'barbell bench squat': 'Sentadilla en banca con barra',
  'barbell bent arm pullover': 'Pullover con brazo flexionado y barra',
  'barbell bent over row': 'Remo inclinado con barra',
  'barbell biceps curl (with arm blaster)': 'Curl de bíceps con barra (con arm blaster)',
  'barbell clean and press': 'Cargada y press con barra',
  'barbell clean-grip front squat': 'Sentadilla frontal agarre de halterofilia con barra',
  'barbell close-grip bench press': 'Press de banca agarre cerrado con barra',
  'barbell curl': 'Curl con barra',
  'barbell deadlift': 'Peso muerto con barra',
  'barbell decline bench press': 'Press de banca declinado con barra',
  'barbell decline bent arm pullover': 'Pullover declinado con brazo flexionado y barra',
  'barbell decline close grip to skull press': 'Press de cráneo declinado agarre cerrado con barra',
  'barbell decline pullover': 'Pullover declinado con barra',
  'barbell decline wide-grip press': 'Press declinado agarre abierto con barra',
  'barbell decline wide-grip pullover': 'Pullover declinado agarre abierto con barra',
  'barbell drag curl': 'Curl arrastrando con barra',
  'barbell floor calf raise': 'Elevación de pantorrillas en suelo con barra',
  'barbell front chest squat': 'Sentadilla frontal de pecho con barra',
  'barbell front raise': 'Elevación frontal con barra',
  'barbell front raise and pullover': 'Elevación frontal y pullover con barra',
  'barbell front squat': 'Sentadilla frontal con barra',
  'barbell full squat': 'Sentadilla completa con barra',
  'barbell full squat (back pov)': 'Sentadilla completa con barra (vista trasera)',
  'barbell full squat (side pov)': 'Sentadilla completa con barra (vista lateral)',
  'barbell full zercher squat': 'Sentadilla Zercher completa con barra',
  'barbell glute bridge': 'Puente de glúteos con barra',
  'barbell glute bridge two legs on bench (male)': 'Puente de glúteos a dos piernas en banca con barra',
  'barbell good morning': 'Buenos días con barra',
  'barbell guillotine bench press': 'Press de banca guillotina con barra',
  'barbell hack squat': 'Sentadilla hack con barra',
  'barbell high bar squat': 'Sentadilla barra alta con barra',
  'barbell incline bench press': 'Press de banca inclinado con barra',
  'barbell incline close grip bench press': 'Press de banca inclinado agarre cerrado con barra',
  'barbell incline reverse-grip press': 'Press inclinado agarre inverso con barra',
  'barbell incline row': 'Remo inclinado con barra',
  'barbell incline shoulder raise': 'Elevación de hombro inclinada con barra',
  'barbell jefferson squat': 'Sentadilla Jefferson con barra',
  'barbell jm bench press': 'Press JM de banca con barra',
  'barbell jump squat': 'Sentadilla con salto de barra',
  'barbell lateral lunge': 'Zancada lateral con barra',
  'barbell low bar squat': 'Sentadilla barra baja con barra',
  'barbell lunge': 'Zancada con barra',
  'barbell lying back of the head tricep extension': 'Extensión de tríceps acostado por detrás de la cabeza con barra',
  'barbell lying close-grip press': 'Press acostado agarre cerrado con barra',
  'barbell lying extension': 'Extensión acostado con barra',
  'barbell lying lifting (on hip)': 'Levantamiento acostado (en cadera) con barra',
  'barbell lying preacher curl': 'Curl de predicador acostado con barra',
  'barbell lying triceps extension': 'Extensión de tríceps acostado con barra',
  'barbell lying triceps extension skull crusher': 'Extensión de tríceps acostado con barra (rompecráneos)',
  'barbell narrow stance squat': 'Sentadilla stance estrecho con barra',
  'barbell one arm bent over row': 'Remo a un brazo inclinado con barra',
  'barbell one arm side deadlift': 'Peso muerto lateral a un brazo con barra',
  'barbell one arm snatch': 'Arrancada a un brazo con barra',
  'barbell one leg squat': 'Sentadilla a una pierna con barra',
  'barbell overhead squat': 'Sentadilla con barra arriba',
  'barbell palms down wrist curl over a bench': 'Curl de muñeca palmas abajo sobre banca con barra',
  'barbell palms up wrist curl over a bench': 'Curl de muñeca palmas arriba sobre banca con barra',
  'barbell pendlay row': 'Remo Pendlay con barra',
  'barbell pin presses': 'Press con pasadores con barra',
  'barbell preacher curl': 'Curl de predicador con barra',
  'barbell press sit-up': 'Abdominal con press de barra',
  'barbell prone incline curl': 'Curl inclinado prono con barra',
  'barbell pullover': 'Pullover con barra',
  'barbell pullover to press': 'Pullover a press con barra',
  'barbell rack pull': 'Jalón de rack con barra',
  'barbell rear delt raise': 'Elevación de deltoides posterior con barra',
  'barbell rear delt row': 'Remo de deltoides posterior con barra',
  'barbell rear lunge': 'Zancada posterior con barra',
  'barbell rear lunge v. 2': 'Zancada posterior con barra v. 2',
  'barbell revers wrist curl v. 2': 'Curl de muñeca inverso con barra v. 2',
  'barbell reverse close-grip bench press': 'Press de banca inverso agarre cerrado con barra',
  'barbell reverse curl': 'Curl inverso con barra',
  'barbell reverse grip bent over row': 'Remo inclinado agarre inverso con barra',
  'barbell reverse grip decline bench press': 'Press de banca declinado agarre inverso con barra',
  'barbell reverse grip incline bench press': 'Press de banca inclinado agarre inverso con barra',
  'barbell reverse grip incline bench row': 'Remo inclinado agarre inverso con barra',
  'barbell reverse grip skullcrusher': 'Rompecráneos agarre inverso con barra',
  'barbell reverse preacher curl': 'Curl de predicador inverso con barra',
  'barbell reverse wrist curl': 'Curl de muñeca inverso con barra',
  'barbell rollerout': 'Rodamiento con barra',
  'barbell rollerout from bench': 'Rodamiento desde banca con barra',
  'barbell romanian deadlift': 'Peso muerto rumano con barra',
  'barbell seated behind head military press': 'Press militar sentado por detrás de la cabeza con barra',
  'barbell seated bradford rocky press': 'Press Bradford Rocky sentado con barra',
  'barbell seated calf raise': 'Elevación de pantorrillas sentado con barra',
  'barbell seated close grip behind neck triceps extension': 'Extensión de tríceps sentado agarre cerrado por detrás del cuello con barra',
  'barbell seated close-grip concentration curl': 'Curl de concentración sentado agarre cerrado con barra',
  'barbell seated good morning': 'Buenos días sentado con barra',
  'barbell seated overhead press': 'Press arriba sentado con barra',
  'barbell seated overhead triceps extension': 'Extensión de tríceps arriba sentado con barra',
  'barbell seated twist': 'Giro sentado con barra',
  'barbell shrug': 'Encogimiento con barra',
  'barbell side bent v. 2': 'Flexión lateral con barra v. 2',
  'barbell side split squat': 'Sentadilla lateral dividida con barra',
  'barbell side split squat v. 2': 'Sentadilla lateral dividida con barra v. 2',
  'barbell single leg deadlift': 'Peso muerto a una pierna con barra',
  'barbell single leg split squat': 'Sentadilla dividida a una pierna con barra',
  'barbell sitted alternate leg raise': 'Elevación de pierna alterna sentado con barra',
  'barbell sitted alternate leg raise (female)': 'Elevación de pierna alterna sentado con barra',
  'barbell skier': 'Esquiador con barra',
  'barbell speed squat': 'Sentadilla rápida con barra',
  'barbell split squat v. 2': 'Sentadilla dividida con barra v. 2',
  'barbell squat (on knees)': 'Sentadilla con barra (de rodillas)',
  'barbell squat jump step rear lunge': 'Sentadilla con salto y zancada posterior con barra',
  'barbell standing ab rollerout': 'Rodamiento abdominal de pie con barra',
  'barbell standing back wrist curl': 'Curl de muñeca de pie por detrás con barra',
  'barbell standing bradford press': 'Press Bradford de pie con barra',
  'barbell standing calf raise': 'Elevación de pantorrillas de pie con barra',
  'barbell standing close grip curl': 'Curl agarre cerrado de pie con barra',
  'barbell standing close grip military press': 'Press militar agarre cerrado de pie con barra',
  'barbell standing concentration curl': 'Curl de concentración de pie con barra',
  'barbell standing front raise over head': 'Elevación frontal arriba de la cabeza de pie con barra',
  'barbell standing leg calf raise': 'Elevación de pantorrillas de pie con barra',
  'barbell standing overhead triceps extension': 'Extensión de tríceps arriba de pie con barra',
  'barbell standing reverse grip curl': 'Curl agarre inverso de pie con barra',
  'barbell standing rocking leg calf raise': 'Elevación de pantorrillas balanceando de pie con barra',
  'barbell standing twist': 'Giro de pie con barra',
  'barbell standing wide grip biceps curl': 'Curl de bíceps agarre abierto de pie con barra',
  'barbell standing wide military press': 'Press militar agarre abierto de pie con barra',
  'barbell standing wide-grip curl': 'Curl agarre abierto de pie con barra',
  'barbell step-up': 'Step-up con barra',
  'barbell stiff leg good morning': 'Buenos días con piernas rígidas con barra',
  'barbell straight leg deadlift': 'Peso muerto con piernas rectas con barra',
  'barbell thruster': 'Thruster con barra',
  'barbell upright row': 'Remo al mentón con barra',
  'barbell upright row v. 2': 'Remo al mentón con barra v. 2',
  'barbell upright row v. 3': 'Remo al mentón con barra v. 3',
  'barbell wide bench press': 'Press de banca abierto con barra',
  'barbell wide reverse grip bench press': 'Press de banca inverso abierto con barra',
  'barbell wide squat': 'Sentadilla abierta con barra',
  'barbell wide-grip upright row': 'Remo al mentón agarre abierto con barra',
  'barbell wrist curl': 'Curl de muñeca con barra',
  'barbell wrist curl v. 2': 'Curl de muñeca con barra v. 2',
  'barbell zercher squat': 'Sentadilla Zercher con barra',
  'basic toe touch (male)': 'Toque básico de pies',
  'battling ropes': 'Cuerdas de batalla',
  'bear crawl': 'Caminata de oso',
  'behind head chest stretch': 'Estiramiento de pecho por detrás de la cabeza',
  'bench dip (knees bent)': 'Fondos de banca (rodillas flexionadas)',
  'bench dip on floor': 'Fondos de banca en suelo',
  'bench hip extension': 'Extensión de cadera en banca',
  'bent knee lying twist (male)': 'Giro acostado con rodillas flexionadas',
  'biceps narrow pull-ups': 'Dominadas de bíceps agarre estrecho',
  'biceps pull-up': 'Dominada de bíceps',
  'body-up': 'Body-up',
  'bodyweight drop jump squat': 'Sentadilla con salto de caída en peso corporal',
  'bodyweight incline side plank': 'Plancha lateral inclinada en peso corporal',
  'bodyweight kneeling triceps extension': 'Extensión de tríceps arrodillado en peso corporal',
  'bodyweight side lying biceps curl': 'Curl de bíceps acostado lateral en peso corporal',
  'bodyweight squatting row': 'Remo en sentadilla en peso corporal',
  'bodyweight squatting row (with towel)': 'Remo en sentadilla (con toalla) en peso corporal',
  'bodyweight standing calf raise': 'Elevación de pantorrillas de pie en peso corporal',
  'bodyweight standing close-grip one arm row': 'Remo a un brazo agarre cerrado de pie en peso corporal',
  'bodyweight standing close-grip row': 'Remo agarre cerrado de pie en peso corporal',
  'bodyweight standing one arm row': 'Remo a un brazo de pie en peso corporal',
  'bodyweight standing one arm row (with towel)': 'Remo a un brazo de pie (con toalla) en peso corporal',
  'bodyweight standing row': 'Remo de pie en peso corporal',
  'bodyweight standing row (with towel)': 'Remo de pie (con toalla) en peso corporal',
  'box jump down with one leg stabilization': 'Salto de caja con estabilización a una pierna',
  'burpee': 'Burpee',
  'butt-ups': 'Elevación de glúteos',
  'cable alternate shoulder press': 'Press de hombro alterno en polea',
  'cable alternate triceps extension': 'Extensión de tríceps alterna en polea',
  'cable assisted inverse leg curl': 'Curl de pierna inverso asistido en polea',
  'cable bar lateral pulldown': 'Jalón lateral con barra en polea',
  'cable bench press': 'Press de banca en polea',
  'cable close grip curl': 'Curl agarre cerrado en polea',
  'cable concentration curl': 'Curl de concentración en polea',
  'cable concentration extension (on knee)': 'Extensión de concentración (en rodilla) en polea',
  'cable cross-over lateral pulldown': 'Jalón lateral crossover en polea',
  'cable cross-over revers fly': 'Apertura inversa crossover en polea',
  'cable cross-over variation': 'Variación crossover en polea',
  'cable curl': 'Curl en polea',
  'cable deadlift': 'Peso muerto en polea',
  'cable decline fly': 'Apertura declinada en polea',
  'cable decline one arm press': 'Press declinado a un brazo en polea',
  'cable decline press': 'Press declinado en polea',
  'cable decline seated wide-grip row': 'Remo sentado agarre abierto declinado en polea',
  'cable drag curl': 'Curl arrastrando en polea',
  'cable floor seated wide-grip row': 'Remo sentado agarre abierto en suelo con polea',
  'cable forward raise': 'Elevación frontal en polea',
  'cable front raise': 'Elevación frontal en polea',
  'cable front shoulder raise': 'Elevación frontal de hombro en polea',
  'cable hammer curl (with rope)': 'Curl martillo en polea (con cuerda)',
  'cable high pulley overhead tricep extension': 'Extensión de tríceps arriba en polea de alto',
  'cable high row (kneeling)': 'Remo alto en polea (arrodillado)',
  'cable hip adduction': 'Aducción de cadera en polea',
  'cable incline bench press': 'Press de banca inclinado en polea',
  'cable incline bench row': 'Remo inclinado en polea',
  'cable incline fly': 'Apertura inclinada en polea',
  'cable incline fly (on stability ball)': 'Apertura inclinada en polea (sobre balón)',
  'cable incline pushdown': 'Empuje inclinado en polea',
  'cable incline triceps extension': 'Extensión de tríceps inclinada en polea',
  'cable judo flip': 'Lanzamiento de judo en polea',
  'cable kickback': 'Extensión de tríceps en polea',
  'cable kneeling crunch': 'Crunch arrodillado en polea',
  'cable kneeling rear delt row (with rope) (male)': 'Remo de deltoides posterior arrodillado en polea (con cuerda)',
  'cable lat pulldown full range of motion': 'Jalón de dorsal en polea rango completo',
  'cable lateral pulldown (with rope attachment)': 'Jalón lateral en polea (con cuerda)',
  'cable lateral pulldown with v-bar': 'Jalón lateral con V-barra en polea',
  'cable lateral raise': 'Elevación lateral en polea',
  'cable low fly': 'Apertura baja en polea',
  'cable low seated row': 'Remo sentado bajo en polea',
  'cable lying bicep curl': 'Curl de bíceps acostado en polea',
  'cable lying close-grip curl': 'Curl agarre cerrado acostado en polea',
  'cable lying extension pullover (with rope attachment)': 'Extensión pullover acostado en polea (con cuerda)',
  'cable lying fly': 'Apertura acostado en polea',
  'cable lying triceps extension v. 2': 'Extensión de tríceps acostado en polea v. 2',
  'cable middle fly': 'Apertura media en polea',
  'cable one arm bent over row': 'Remo a un brazo inclinado en polea',
  'cable one arm curl': 'Curl a un brazo en polea',
  'cable one arm decline chest fly': 'Apertura de pecho declinado a un brazo en polea',
  'cable one arm fly on exercise ball': 'Apertura a un brazo en balón de ejercicio con polea',
  'cable one arm incline fly on exercise ball': 'Apertura inclinada a un brazo en balón de ejercicio con polea',
  'cable one arm incline press': 'Press inclinado a un brazo en polea',
  'cable one arm incline press on exercise ball': 'Press inclinado a un brazo en balón de ejercicio con polea',
  'cable one arm lateral bent-over': 'Lateral a un brazo inclinado en polea',
  'cable one arm lateral raise': 'Elevación lateral a un brazo en polea',
  'cable one arm preacher curl': 'Curl de predicador a un brazo en polea',
  'cable one arm press on exercise ball': 'Press a un brazo en balón de ejercicio con polea',
  'cable one arm pulldown': 'Jalón a un brazo en polea',
  'cable one arm reverse preacher curl': 'Curl de predicador inverso a un brazo en polea',
  'cable one arm straight back high row (kneeling)': 'Remo alto a un brazo espalda recta arrodillado en polea',
  'cable one arm tricep pushdown': 'Empuje de tríceps a un brazo en polea',
  'cable overhead curl': 'Curl arriba en polea',
  'cable overhead curl on exercise ball': 'Curl arriba en balón de ejercicio con polea',
  'cable overhead triceps extension (rope attachment)': 'Extensión de tríceps arriba en polea (con cuerda)',
  'cable palm rotational row': 'Remo rotativo de palma en polea',
  'cable preacher curl': 'Curl de predicador en polea',
  'cable press on exercise ball': 'Press en balón de ejercicio con polea',
  'cable pull through (with rope)': 'Jalón cruzado en polea (con cuerda)',
  'cable pulldown': 'Jalón en polea',
  'cable pulldown (pro lat bar)': 'Jalón en polea (barra pro lat)',
  'cable pulldown bicep curl': 'Curl de bíceps en jalón de polea',
  'cable pushdown': 'Empuje en polea',
  'cable pushdown (straight arm) v. 2': 'Empuje en polea (brazo recto) v. 2',
  'cable pushdown (with rope attachment)': 'Empuje en polea (con cuerda)',
  'cable rear delt row (stirrups)': 'Remo de deltoides posterior en polea (estribos)',
  'cable rear delt row (with rope)': 'Remo de deltoides posterior en polea (con cuerda)',
  'cable rear drive': 'Tracción posterior en polea',
  'cable rear pulldown': 'Jalón posterior en polea',
  'cable reverse crunch': 'Crunch inverso en polea',
  'cable reverse curl': 'Curl inverso en polea',
  'cable reverse grip triceps pushdown (sz-bar) (with arm blaster)': 'Empuje de tríceps agarre inverso en polea (barra SZ) (con arm blaster)',
  'cable reverse one arm curl': 'Curl inverso a un brazo en polea',
  'cable reverse preacher curl': 'Curl de predicador inverso en polea',
  'cable reverse wrist curl': 'Curl de muñeca inverso en polea',
  'cable reverse-grip pushdown': 'Empuje agarre inverso en polea',
  'cable reverse-grip straight back seated high row': 'Remo alto sentado espalda recta agarre inverso en polea',
  'cable rope crossover seated row': 'Remo sentado crossover con cuerda en polea',
  'cable rope elevated seated row': 'Remo sentado elevado con cuerda en polea',
  'cable rope extension incline bench row': 'Remo inclinado con extensión de cuerda en polea',
  'cable rope hammer preacher curl': 'Curl de predicador martillo con cuerda en polea',
  'cable rope high pulley overhead tricep extension': 'Extensión de tríceps arriba con cuerda en polea de alto',
  'cable rope incline tricep extension': 'Extensión de tríceps inclinada con cuerda en polea',
  'cable rope lying on floor tricep extension': 'Extensión de tríceps acostado en suelo con cuerda en polea',
  'cable rope one arm hammer preacher curl': 'Curl de predicador martillo a un brazo con cuerda en polea',
  'cable rope seated row': 'Remo sentado con cuerda en polea',
  'cable russian twists (on stability ball)': 'Giros rusos en polea (sobre balón)',
  'cable seated chest press': 'Press de pecho sentado en polea',
  'cable seated crunch': 'Crunch sentado en polea',
  'cable seated curl': 'Curl sentado en polea',
  'cable seated high row (v-bar)': 'Remo alto sentado (V-barra) en polea',
  'cable seated one arm alternate row': 'Remo alterno a un brazo sentado en polea',
  'cable seated one arm concentration curl': 'Curl de concentración a un brazo sentado en polea',
  'cable seated overhead curl': 'Curl arriba sentado en polea',
  'cable seated rear lateral raise': 'Elevación lateral posterior sentado en polea',
  'cable seated row': 'Remo sentado en polea',
  'cable seated shoulder internal rotation': 'Rotación interna de hombro sentado en polea',
  'cable seated twist': 'Giro sentado en polea',
  'cable seated wide-grip row': 'Remo sentado agarre abierto en polea',
  'cable shoulder press': 'Press de hombro en polea',
  'cable shrug': 'Encogimiento en polea',
  'cable side bend': 'Flexión lateral en polea',
  'cable side bend crunch (bosu ball)': 'Crunch con flexión lateral en polea (bosu)',
  'cable side crunch': 'Crunch lateral en polea',
  'cable squat row (with rope attachment)': 'Remo en sentadilla en polea (con cuerda)',
  'cable squatting curl': 'Curl en sentadilla en polea',
  'cable standing back wrist curl': 'Curl de muñeca de pie por detrás en polea',
  'cable standing calf raise': 'Elevación de pantorrillas de pie en polea',
  'cable standing cross-over high reverse fly': 'Apertura inversa alta crossover de pie en polea',
  'cable standing crunch': 'Crunch de pie en polea',
  'cable standing crunch (with rope attachment)': 'Crunch de pie en polea (con cuerda)',
  'cable standing fly': 'Apertura de pie en polea',
  'cable standing hip extension': 'Extensión de cadera de pie en polea',
  'cable standing inner curl': 'Curl interior de pie en polea',
  'cable standing lift': 'Levantamiento de pie en polea',
  'cable standing one arm triceps extension': 'Extensión de tríceps a un brazo de pie en polea',
  'cable standing one leg calf raise': 'Elevación de pantorrillas a una pierna de pie en polea',
  'cable standing pulldown (with rope)': 'Jalón de pie (con cuerda) en polea',
  'cable standing rear delt row (with rope)': 'Remo de deltoides posterior de pie en polea (con cuerda)',
  'cable standing reverse grip one arm overhead tricep extension': 'Extensión de tríceps a un brazo arriba agarre inverso de pie en polea',
  'cable standing row (v-bar)': 'Remo de pie (V-barra) en polea',
  'cable standing shoulder external rotation': 'Rotación externa de hombro de pie en polea',
  'cable standing twist row (v-bar)': 'Remo con giro de pie en polea (V-barra)',
  'cable standing up straight crossovers': 'Crossover recto de pie en polea',
  'cable straight arm pulldown': 'Jalón brazo recto en polea',
  'cable straight arm pulldown (with rope)': 'Jalón brazo recto en polea (con cuerda)',
  'cable straight back seated row': 'Remo sentado espalda recta en polea',
  'cable supine reverse fly': 'Apertura inversa supino en polea',
  'cable thibaudeau kayak row': 'Remo kayak Thibaudeau en polea',
  'cable triceps pushdown (v-bar)': 'Empuje de tríceps (V-barra) en polea',
  'cable triceps pushdown (v-bar) (with arm blaster)': 'Empuje de tríceps (V-barra) en polea (con arm blaster)',
  'cable tuck reverse crunch': 'Crunch inverso tuck en polea',
  'cable twist': 'Giro en polea',
  'cable twist (up-down)': 'Giro en polea (arriba-abajo)',
  'cable twisting pull': 'Jalón giratorio en polea',
  'cable two arm curl on incline bench': 'Curl a dos brazos en banca inclinada con polea',
  'cable two arm tricep kickback': 'Extensión de tríceps a dos brazos en polea',
  'cable underhand pulldown': 'Jalón supino en polea',
  'cable upper chest crossovers': 'Crossover de pecho superior en polea',
  'cable upper row': 'Remo alto en polea',
  'cable upright row': 'Remo al mentón en polea',
  'cable wide grip rear pulldown behind neck': 'Jalón posterior agarre abierto por detrás del cuello en polea',
  'cable wrist curl': 'Curl de muñeca en polea',
  'calf push stretch with hands against wall': 'Estiramiento de empuje de pantorrillas contra pared',
  'calf stretch with hands against wall': 'Estiramiento de pantorrillas contra pared',
  'calf stretch with rope': 'Estiramiento de pantorrillas con cuerda',
  'chest and front of shoulder stretch': 'Estiramiento de pecho y parte anterior del hombro',
  'chest dip': 'Fondos para pecho',
  'chest dip (on dip-pull-up cage)': 'Fondos para pecho (en jaula de fondos)',
  'chest dip on straight bar': 'Fondos para pecho en barra recta',
  'chest stretch with exercise ball': 'Estiramiento de pecho con balón de ejercicio',
  'chest tap push-up (male)': 'Flexión de brazos con toque de pecho',
  'chin-up': 'Dominada agarre supino',
  'chin-ups (narrow parallel grip)': 'Dominadas agarre paralelo estrecho',
  'circles knee stretch': 'Círculos de rodilla estiramiento',
  'clap push up': 'Flexión de brazos con palmada',
  'clock push-up': 'Flexión de brazos reloj',
  'close grip chin-up': 'Dominada agarre supino cerrado',
  'close-grip push-up': 'Flexión de brazos agarre cerrado',
  'close-grip push-up (on knees)': 'Flexión de brazos agarre cerrado (de rodillas)',
  'cocoons': 'Cacahuates',
  'cross body crunch': 'Crunch cruzado',
  'crunch (hands overhead)': 'Crunch (manos arriba)',
  'crunch (on stability ball)': 'Crunch (sobre balón)',
  'crunch (on stability ball, arms straight)': 'Crunch (sobre balón, brazos rectos)',
  'crunch floor': 'Crunch en suelo',
  'curl-up': 'Encogimiento abdominal',
  'cycle cross trainer': 'Elíptica',
  'dead bug': 'Bicho muerto',
  'decline crunch': 'Crunch declinado',
  'decline push-up': 'Flexión de brazos declinada',
  'decline sit-up': 'Abdominal declinado',
  'deep push up': 'Flexión de brazos profunda',
  'diamond push-up': 'Flexión de brazos diamante',
  'drop push up': 'Flexión de brazos con caída',
  'dumbbell alternate biceps curl': 'Curl alterno de bíceps con mancuerna',
  'dumbbell alternate biceps curl (with arm blaster)': 'Curl alterno de bíceps con mancuerna (con arm blaster)',
  'dumbbell alternate hammer preacher curl': 'Curl de predicador martillo alterno con mancuerna',
  'dumbbell alternate preacher curl': 'Curl de predicador alterno con mancuerna',
  'dumbbell alternate seated hammer curl': 'Curl martillo alterno sentado con mancuerna',
  'dumbbell alternate side press': 'Press lateral alterno con mancuerna',
  'dumbbell alternating bicep curl with leg raised on exercise ball': 'Curl alterno de bíceps con pierna elevada en balón con mancuerna',
  'dumbbell alternating seated bicep curl on exercise ball': 'Curl alterno sentado de bíceps en balón con mancuerna',
  'dumbbell arnold press': 'Press Arnold con mancuerna',
  'dumbbell arnold press v. 2': 'Press Arnold con mancuerna v. 2',
  'dumbbell around pullover': 'Pullover alrededor con mancuerna',
  'dumbbell bench press': 'Press de banca con mancuerna',
  'dumbbell bench seated press': 'Press sentado de banca con mancuerna',
  'dumbbell bench squat': 'Sentadilla de banca con mancuerna',
  'dumbbell bent over row': 'Remo inclinado con mancuerna',
  'dumbbell bicep curl lunge with bowling motion': 'Zancada con curl de bíceps con mancuerna y movimiento de bowling',
  'dumbbell bicep curl on exercise ball with leg raised': 'Curl de bíceps con mancuerna en balón con pierna elevada',
  'dumbbell bicep curl with stork stance': 'Curl de bíceps con mancuerna en postura de cigüeña',
  'dumbbell biceps curl': 'Curl de bíceps con mancuerna',
  'dumbbell biceps curl (with arm blaster)': 'Curl de bíceps con mancuerna (con arm blaster)',
  'dumbbell biceps curl reverse': 'Curl de bíceps inverso con mancuerna',
  'dumbbell biceps curl squat': 'Sentadilla con curl de bíceps con mancuerna',
  'dumbbell biceps curl v sit on bosu ball': 'Curl de bíceps con mancuerna en V-sit en bosu',
  'dumbbell burpee': 'Burpee con mancuerna',
  'dumbbell clean': 'Cargada con mancuerna',
  'dumbbell close grip press': 'Press agarre cerrado con mancuerna',
  'dumbbell close-grip press': 'Press agarre cerrado con mancuerna',
  'dumbbell concentration curl': 'Curl de concentración con mancuerna',
  'dumbbell contralateral forward lunge': 'Zancada frontal contralateral con mancuerna',
  'dumbbell cross body hammer curl': 'Curl martillo cruzado con mancuerna',
  'dumbbell cross body hammer curl v. 2': 'Curl martillo cruzado con mancuerna v. 2',
  'dumbbell cuban press': 'Press cubano con mancuerna',
  'dumbbell cuban press v. 2': 'Press cubano con mancuerna v. 2',
  'dumbbell deadlift': 'Peso muerto con mancuerna',
  'dumbbell decline bench press': 'Press de banca declinado con mancuerna',
  'dumbbell decline fly': 'Apertura declinada con mancuerna',
  'dumbbell decline hammer press': 'Press martillo declinado con mancuerna',
  'dumbbell decline one arm fly': 'Apertura declinada a un brazo con mancuerna',
  'dumbbell decline one arm hammer press': 'Press martillo declinado a un brazo con mancuerna',
  'dumbbell decline shrug': 'Encogimiento declinado con mancuerna',
  'dumbbell decline shrug v. 2': 'Encogimiento declinado con mancuerna v. 2',
  'dumbbell decline triceps extension': 'Extensión de tríceps declinada con mancuerna',
  'dumbbell decline twist fly': 'Apertura declinada giratoria con mancuerna',
  'dumbbell finger curls': 'Curl de dedos con mancuerna',
  'dumbbell fly': 'Apertura con mancuerna',
  'dumbbell fly on exercise ball': 'Apertura con mancuerna en balón de ejercicio',
  'dumbbell forward lunge triceps extension': 'Extensión de tríceps en zancada frontal con mancuerna',
  'dumbbell front raise': 'Elevación frontal con mancuerna',
  'dumbbell front raise v. 2': 'Elevación frontal con mancuerna v. 2',
  'dumbbell full can lateral raise': 'Elevación lateral con lata llena con mancuerna',
  'dumbbell goblet squat': 'Sentadilla goblet con mancuerna',
  'dumbbell hammer curl': 'Curl martillo con mancuerna',
  'dumbbell hammer curl on exercise ball': 'Curl martillo con mancuerna en balón de ejercicio',
  'dumbbell hammer curl v. 2': 'Curl martillo con mancuerna v. 2',
  'dumbbell hammer curls (with arm blaster)': 'Curl martillo con mancuerna (con arm blaster)',
  'dumbbell high curl': 'Curl alto con mancuerna',
  'dumbbell incline alternate press': 'Press alterno inclinado con mancuerna',
  'dumbbell incline bench press': 'Press de banca inclinado con mancuerna',
  'dumbbell incline biceps curl': 'Curl de bíceps inclinado con mancuerna',
  'dumbbell incline breeding': 'Press inclinado con mancuerna',
  'dumbbell incline curl': 'Curl inclinado con mancuerna',
  'dumbbell incline curl v. 2': 'Curl inclinado con mancuerna v. 2',
  'dumbbell incline fly': 'Apertura inclinada con mancuerna',
  'dumbbell incline fly on exercise ball': 'Apertura inclinada con mancuerna en balón de ejercicio',
  'dumbbell incline hammer curl': 'Curl martillo inclinado con mancuerna',
  'dumbbell incline hammer press': 'Press martillo inclinado con mancuerna',
  'dumbbell incline hammer press on exercise ball': 'Press martillo inclinado con mancuerna en balón de ejercicio',
  'dumbbell incline inner biceps curl': 'Curl interior de bíceps inclinado con mancuerna',
  'dumbbell incline one arm fly': 'Apertura inclinada a un brazo con mancuerna',
  'dumbbell incline one arm fly on exercise ball': 'Apertura inclinada a un brazo con mancuerna en balón de ejercicio',
  'dumbbell incline one arm hammer press': 'Press martillo inclinado a un brazo con mancuerna',
  'dumbbell incline one arm hammer press on exercise ball': 'Press martillo inclinado a un brazo con mancuerna en balón de ejercicio',
  'dumbbell incline one arm lateral raise': 'Elevación lateral inclinada a un brazo con mancuerna',
  'dumbbell incline one arm press': 'Press inclinado a un brazo con mancuerna',
  'dumbbell incline one arm press on exercise ball': 'Press inclinado a un brazo con mancuerna en balón de ejercicio',
  'dumbbell incline palm-in press': 'Press inclinado palmas hacia adentro con mancuerna',
  'dumbbell incline press on exercise ball': 'Press inclinado con mancuerna en balón de ejercicio',
  'dumbbell incline raise': 'Elevación inclinada con mancuerna',
  'dumbbell incline rear lateral raise': 'Elevación lateral posterior inclinada con mancuerna',
  'dumbbell incline row': 'Remo inclinado con mancuerna',
  'dumbbell incline shrug': 'Encogimiento inclinado con mancuerna',
  'dumbbell incline t-raise': 'Elevación en T inclinada con mancuerna',
  'dumbbell incline triceps extension': 'Extensión de tríceps inclinada con mancuerna',
  'dumbbell incline twisted flyes': 'Aperturas inclinadas giratorias con mancuerna',
  'dumbbell incline two arm extension': 'Extensión a dos brazos inclinada con mancuerna',
  'dumbbell incline y-raise': 'Elevación en Y inclinada con mancuerna',
  'dumbbell iron cross': 'Cruz de hierro con mancuerna',
  'dumbbell kickback': 'Extensión de tríceps con mancuerna',
  'dumbbell kickbacks on exercise ball': 'Extensiones de tríceps con mancuerna en balón de ejercicio',
  'dumbbell kneeling bicep curl exercise ball': 'Curl de bíceps arrodillado con mancuerna en balón de ejercicio',
  'dumbbell lateral raise': 'Elevación lateral con mancuerna',
  'dumbbell lateral to front raise': 'Elevación lateral a frontal con mancuerna',
  'dumbbell lunge': 'Zancada con mancuerna',
  'dumbbell lunge with bicep curl': 'Zancada con curl de bíceps y mancuerna',
  'dumbbell lying alternate extension': 'Extensión alterna acostado con mancuerna',
  'dumbbell lying elbow press': 'Press de codo acostado con mancuerna',
  'dumbbell lying extension (across face)': 'Extensión acostado (cruzando la cara) con mancuerna',
  'dumbbell lying external shoulder rotation': 'Rotación externa de hombro acostado con mancuerna',
  'dumbbell lying femoral': 'Femoral acostado con mancuerna',
  'dumbbell lying hammer press': 'Press martillo acostado con mancuerna',
  'dumbbell lying on floor rear delt raise': 'Elevación de deltoides posterior acostado en suelo con mancuerna',
  'dumbbell lying one arm deltoid rear': 'Deltoides posterior a un brazo acostado con mancuerna',
  'dumbbell lying one arm press': 'Press a un brazo acostado con mancuerna',
  'dumbbell lying one arm press v. 2': 'Press a un brazo acostado con mancuerna v. 2',
  'dumbbell lying one arm pronated triceps extension': 'Extensión de tríceps a un brazo acostado prono con mancuerna',
  'dumbbell lying one arm rear lateral raise': 'Elevación lateral posterior a un brazo acostado con mancuerna',
  'dumbbell lying one arm supinated triceps extension': 'Extensión de tríceps a un brazo acostado supino con mancuerna',
  'dumbbell lying pronation': 'Pronación acostado con mancuerna',
  'dumbbell lying pronation on floor': 'Pronación acostado en suelo con mancuerna',
  'dumbbell lying pullover on exercise ball': 'Pullover acostado con mancuerna en balón de ejercicio',
  'dumbbell lying rear delt row': 'Remo de deltoides posterior acostado con mancuerna',
  'dumbbell lying rear lateral raise': 'Elevación lateral posterior acostado con mancuerna',
  'dumbbell lying single extension': 'Extensión simple acostado con mancuerna',
  'dumbbell lying supination': 'Supinación acostado con mancuerna',
  'dumbbell lying supination on floor': 'Supinación acostado en suelo con mancuerna',
  'dumbbell lying supine biceps curl': 'Curl de bíceps supino acostado con mancuerna',
  'dumbbell lying supine curl': 'Curl supino acostado con mancuerna',
  'dumbbell lying triceps extension': 'Extensión de tríceps acostado con mancuerna',
  'dumbbell lying wide curl': 'Curl abierto acostado con mancuerna',
  'dumbbell neutral grip bench press': 'Press de banca agarre neutro con mancuerna',
  'dumbbell one arm bench fly': 'Apertura a un brazo en banca con mancuerna',
  'dumbbell one arm bent-over row': 'Remo a un brazo inclinado con mancuerna',
  'dumbbell one arm chest fly on exercise ball': 'Apertura de pecho a un brazo en balón con mancuerna',
  'dumbbell one arm concentration curl (on stability ball)': 'Curl de concentración a un brazo (en balón) con mancuerna',
  'dumbbell one arm decline chest press': 'Press de pecho declinado a un brazo con mancuerna',
  'dumbbell one arm fly on exercise ball': 'Apertura a un brazo en balón de ejercicio con mancuerna',
  'dumbbell one arm french press on exercise ball': 'Press francés a un brazo en balón de ejercicio con mancuerna',
  'dumbbell one arm hammer preacher curl': 'Curl de predicador martillo a un brazo con mancuerna',
  'dumbbell one arm hammer press on exercise ball': 'Press martillo a un brazo en balón de ejercicio con mancuerna',
  'dumbbell one arm incline chest press': 'Press de pecho inclinado a un brazo con mancuerna',
  'dumbbell one arm kickback': 'Extensión de tríceps a un brazo con mancuerna',
  'dumbbell one arm lateral raise': 'Elevación lateral a un brazo con mancuerna',
  'dumbbell one arm lateral raise with support': 'Elevación lateral a un brazo con apoyo y mancuerna',
  'dumbbell one arm press on exercise ball': 'Press a un brazo en balón de ejercicio con mancuerna',
  'dumbbell one arm prone curl': 'Curl a un brazo prono con mancuerna',
  'dumbbell one arm prone hammer curl': 'Curl martillo a un brazo prono con mancuerna',
  'dumbbell one arm reverse fly (with support)': 'Apertura inversa a un brazo con mancuerna (con apoyo)',
  'dumbbell one arm reverse grip press': 'Press agarre inverso a un brazo con mancuerna',
  'dumbbell one arm reverse preacher curl': 'Curl de predicador inverso a un brazo con mancuerna',
  'dumbbell one arm reverse spider curl': 'Curl de araña inverso a un brazo con mancuerna',
  'dumbbell one arm reverse wrist curl': 'Curl de muñeca inverso a un brazo con mancuerna',
  'dumbbell one arm seated bicep curl on exercise ball': 'Curl de bíceps a un brazo sentado en balón de ejercicio con mancuerna',
  'dumbbell one arm seated hammer curl': 'Curl martillo a un brazo sentado con mancuerna',
  'dumbbell one arm seated neutral wrist curl': 'Curl de muñeca neutro a un brazo sentado con mancuerna',
  'dumbbell one arm shoulder press': 'Press de hombro a un brazo con mancuerna',
  'dumbbell one arm shoulder press v. 2': 'Press de hombro a un brazo con mancuerna v. 2',
  'dumbbell one arm snatch': 'Arrancada a un brazo con mancuerna',
  'dumbbell one arm standing curl': 'Curl a un brazo de pie con mancuerna',
  'dumbbell one arm standing hammer curl': 'Curl martillo a un brazo de pie con mancuerna',
  'dumbbell one arm triceps extension (on bench)': 'Extensión de tríceps a un brazo (en banca) con mancuerna',
  'dumbbell one arm upright row': 'Remo al mentón a un brazo con mancuerna',
  'dumbbell one arm wrist curl': 'Curl de muñeca a un brazo con mancuerna',
  'dumbbell one arm zottman preacher curl': 'Curl de predicador Zottman a un brazo con mancuerna',
  'dumbbell one leg fly on exercise ball': 'Apertura a una pierna en balón de ejercicio con mancuerna',
  'dumbbell over bench neutral wrist curl': 'Curl de muñeca neutro sobre banca con mancuerna',
  'dumbbell over bench one arm neutral wrist curl': 'Curl de muñeca neutro a un brazo sobre banca con mancuerna',
  'dumbbell over bench one arm reverse wrist curl': 'Curl de muñeca inverso a un brazo sobre banca con mancuerna',
  'dumbbell over bench one arm wrist curl': 'Curl de muñeca a un brazo sobre banca con mancuerna',
  'dumbbell over bench revers wrist curl': 'Curl de muñeca inverso sobre banca con mancuerna',
  'dumbbell over bench wrist curl': 'Curl de muñeca sobre banca con mancuerna',
  'dumbbell palm rotational bent over row': 'Remo inclinado rotativo de palma con mancuerna',
  'dumbbell palms in incline bench press': 'Press de banca inclinado palmas hacia adentro con mancuerna',
  'dumbbell peacher hammer curl': 'Curl martillo de predicador con mancuerna',
  'dumbbell plyo squat': 'Sentadilla pliométrica con mancuerna',
  'dumbbell preacher curl': 'Curl de predicador con mancuerna',
  'dumbbell preacher curl over exercise ball': 'Curl de predicador con mancuerna sobre balón de ejercicio',
  'dumbbell press on exercise ball': 'Press con mancuerna en balón de ejercicio',
  'dumbbell pronate-grip triceps extension': 'Extensión de tríceps agarre prono con mancuerna',
  'dumbbell prone incline curl': 'Curl inclinado prono con mancuerna',
  'dumbbell prone incline hammer curl': 'Curl martillo inclinado prono con mancuerna',
  'dumbbell pullover': 'Pullover con mancuerna',
  'dumbbell pullover hip extension on exercise ball': 'Extensión de cadera en pullover con mancuerna en balón de ejercicio',
  'dumbbell pullover on exercise ball': 'Pullover con mancuerna en balón de ejercicio',
  'dumbbell push press': 'Press de empuje con mancuerna',
  'dumbbell raise': 'Elevación con mancuerna',
  'dumbbell rear delt raise': 'Elevación de deltoides posterior con mancuerna',
  'dumbbell rear delt row_shoulder': 'Remo de deltoides posterior con mancuerna',
  'dumbbell rear fly': 'Apertura posterior con mancuerna',
  'dumbbell rear lateral raise': 'Elevación lateral posterior con mancuerna',
  'dumbbell rear lateral raise (support head)': 'Elevación lateral posterior (apoyando la cabeza) con mancuerna',
  'dumbbell rear lunge': 'Zancada posterior con mancuerna',
  'dumbbell revers grip biceps curl': 'Curl de bíceps agarre inverso con mancuerna',
  'dumbbell reverse bench press': 'Press de banca inverso con mancuerna',
  'dumbbell reverse fly': 'Apertura inversa con mancuerna',
  'dumbbell reverse grip incline bench one arm row': 'Remo a un brazo inclinado agarre inverso con mancuerna',
  'dumbbell reverse grip incline bench two arm row': 'Remo a dos brazos inclinado agarre inverso con mancuerna',
  'dumbbell reverse grip row (female)': 'Remo agarre inverso con mancuerna',
  'dumbbell reverse preacher curl': 'Curl de predicador inverso con mancuerna',
  'dumbbell reverse spider curl': 'Curl de araña inverso con mancuerna',
  'dumbbell reverse wrist curl': 'Curl de muñeca inverso con mancuerna',
  'dumbbell romanian deadlift': 'Peso muerto rumano con mancuerna',
  'dumbbell rotation reverse fly': 'Apertura inversa rotativa con mancuerna',
  'dumbbell scott press': 'Press Scott con mancuerna',
  'dumbbell seated alternate front raise': 'Elevación frontal alterna sentado con mancuerna',
  'dumbbell seated alternate hammer curl on exercise ball': 'Curl martillo alterno sentado en balón de ejercicio con mancuerna',
  'dumbbell seated alternate press': 'Press alterno sentado con mancuerna',
  'dumbbell seated alternate shoulder': 'Hombro alterno sentado con mancuerna',
  'dumbbell seated bench extension': 'Extensión sentado de banca con mancuerna',
  'dumbbell seated bent arm lateral raise': 'Elevación lateral con brazo flexionado sentado con mancuerna',
  'dumbbell seated bent over alternate kickback': 'Extensión alterna inclinada sentado con mancuerna',
  'dumbbell seated bent over triceps extension': 'Extensión de tríceps inclinada sentado con mancuerna',
  'dumbbell seated bicep curl': 'Curl de bíceps sentado con mancuerna',
  'dumbbell seated biceps curl (on stability ball)': 'Curl de bíceps sentado (en balón) con mancuerna',
  'dumbbell seated biceps curl to shoulder press': 'Curl de bíceps sentado a press de hombro con mancuerna',
  'dumbbell seated calf raise': 'Elevación de pantorrillas sentado con mancuerna',
  'dumbbell seated curl': 'Curl sentado con mancuerna',
  'dumbbell seated front raise': 'Elevación frontal sentado con mancuerna',
  'dumbbell seated hammer curl': 'Curl martillo sentado con mancuerna',
  'dumbbell seated inner biceps curl': 'Curl interior de bíceps sentado con mancuerna',
  'dumbbell seated kickback': 'Extensión de tríceps sentado con mancuerna',
  'dumbbell seated lateral raise': 'Elevación lateral sentado con mancuerna',
  'dumbbell seated lateral raise v. 2': 'Elevación lateral sentado con mancuerna v. 2',
  'dumbbell seated neutral wrist curl': 'Curl de muñeca neutro sentado con mancuerna',
  'dumbbell seated one arm bicep curl on exercise ball with leg raised': 'Curl de bíceps a un brazo sentado en balón con pierna elevada y mancuerna',
  'dumbbell seated one arm kickback': 'Extensión de tríceps a un brazo sentado con mancuerna',
  'dumbbell seated one arm rotate': 'Rotación a un brazo sentado con mancuerna',
  'dumbbell seated one leg calf raise': 'Elevación de pantorrillas a una pierna sentado con mancuerna',
  'dumbbell seated one leg calf raise - hammer grip': 'Elevación de pantorrillas a una pierna sentado agarre martillo con mancuerna',
  'dumbbell seated one leg calf raise - palm up': 'Elevación de pantorrillas a una pierna sentado palma arriba con mancuerna',
  'dumbbell seated palms up wrist curl': 'Curl de muñeca palmas arriba sentado con mancuerna',
  'dumbbell seated preacher curl': 'Curl de predicador sentado con mancuerna',
  'dumbbell seated revers grip concentration curl': 'Curl de concentración agarre inverso sentado con mancuerna',
  'dumbbell seated reverse grip one arm overhead tricep extension': 'Extensión de tríceps a un brazo agarre inverso arriba sentado con mancuerna',
  'dumbbell seated shoulder press': 'Press de hombro sentado con mancuerna',
  'dumbbell seated shoulder press (parallel grip)': 'Press de hombro sentado (agarre paralelo) con mancuerna',
  'dumbbell seated triceps extension': 'Extensión de tríceps sentado con mancuerna',
  'dumbbell shrug': 'Encogimiento con mancuerna',
  'dumbbell side bend': 'Flexión lateral con mancuerna',
  'dumbbell side lying one hand raise': 'Elevación a una mano acostado lateral con mancuerna',
  'dumbbell side plank with rear fly': 'Plancha lateral con apertura posterior con mancuerna',
  'dumbbell single arm overhead carry': 'Transporte a un brazo arriba con mancuerna',
  'dumbbell single leg calf raise': 'Elevación de pantorrillas a una pierna con mancuerna',
  'dumbbell single leg deadlift': 'Peso muerto a una pierna con mancuerna',
  'dumbbell single leg deadlift with stepbox support': 'Peso muerto a una pierna con mancuerna y apoyo en stepbox',
  'dumbbell single leg split squat': 'Sentadilla dividida a una pierna con mancuerna',
  'dumbbell single leg squat': 'Sentadilla a una pierna con mancuerna',
  'dumbbell squat': 'Sentadilla con mancuerna',
  'dumbbell standing alternate hammer curl and press': 'Curl martillo alterno de pie y press con mancuerna',
  'dumbbell standing alternate overhead press': 'Press arriba alterno de pie con mancuerna',
  'dumbbell standing alternate raise': 'Elevación alterna de pie con mancuerna',
  'dumbbell standing alternating tricep kickback': 'Extensión de tríceps alterna de pie con mancuerna',
  'dumbbell standing around world': 'Alrededor del mundo de pie con mancuerna',
  'dumbbell standing bent over one arm triceps extension': 'Extensión de tríceps a un brazo inclinado de pie con mancuerna',
  'dumbbell standing bent over two arm triceps extension': 'Extensión de tríceps a dos brazos inclinado de pie con mancuerna',
  'dumbbell standing biceps curl': 'Curl de bíceps de pie con mancuerna',
  'dumbbell standing calf raise': 'Elevación de pantorrillas de pie con mancuerna',
  'dumbbell standing concentration curl': 'Curl de concentración de pie con mancuerna',
  'dumbbell standing front raise above head': 'Elevación frontal arriba de la cabeza de pie con mancuerna',
  'dumbbell standing inner biceps curl v. 2': 'Curl interior de bíceps de pie con mancuerna v. 2',
  'dumbbell standing kickback': 'Extensión de tríceps de pie con mancuerna',
  'dumbbell standing one arm concentration curl': 'Curl de concentración a un brazo de pie con mancuerna',
  'dumbbell standing one arm curl (over incline bench)': 'Curl a un brazo de pie (sobre banca inclinada) con mancuerna',
  'dumbbell standing one arm curl over incline bench': 'Curl a un brazo de pie sobre banca inclinada con mancuerna',
  'dumbbell standing one arm extension': 'Extensión a un brazo de pie con mancuerna',
  'dumbbell standing one arm palm in press': 'Press a un brazo palmas hacia adentro de pie con mancuerna',
  'dumbbell standing one arm reverse curl': 'Curl inverso a un brazo de pie con mancuerna',
  'dumbbell standing overhead press': 'Press arriba de pie con mancuerna',
  'dumbbell standing palms in press': 'Press palmas hacia adentro de pie con mancuerna',
  'dumbbell standing preacher curl': 'Curl de predicador de pie con mancuerna',
  'dumbbell standing reverse curl': 'Curl inverso de pie con mancuerna',
  'dumbbell standing triceps extension': 'Extensión de tríceps de pie con mancuerna',
  'dumbbell standing zottman preacher curl': 'Curl de predicador Zottman de pie con mancuerna',
  'dumbbell step up single leg balance with bicep curl': 'Step-up a una pierna con equilibrio y curl de bíceps con mancuerna',
  'dumbbell step-up': 'Step-up con mancuerna',
  'dumbbell step-up lunge': 'Step-up zancada con mancuerna',
  'dumbbell step-up split squat': 'Step-up sentadilla dividida con mancuerna',
  'dumbbell stiff leg deadlift': 'Peso muerto con piernas rígidas con mancuerna',
  'dumbbell straight arm pullover': 'Pullover brazo recto con mancuerna',
  'dumbbell straight leg deadlift': 'Peso muerto con piernas rectas con mancuerna',
  'dumbbell sumo pull through': 'Jalón sumo con mancuerna',
  'dumbbell supported squat': 'Sentadilla asistida con mancuerna',
  'dumbbell tate press': 'Press Tate con mancuerna',
  'dumbbell tricep kickback with stork stance': 'Extensión de tríceps en postura de cigüeña con mancuerna',
  'dumbbell twisting bench press': 'Press de banca giratorio con mancuerna',
  'dumbbell upright row': 'Remo al mentón con mancuerna',
  'dumbbell w-press': 'Press en W con mancuerna',
  'dumbbell waiter biceps curl': 'Curl de bíceps de mesero con mancuerna',
  'dumbbell zottman curl': 'Curl Zottman con mancuerna',
  'dumbbell zottman preacher curl': 'Curl de predicador Zottman con mancuerna',
  'dumbbells seated triceps extension': 'Extensión de tríceps sentado con mancuernas',
  'dynamic chest stretch (male)': 'Estiramiento dinámico de pecho',
  'elbow dips': 'Fondos de codo',
  'elbow lift - reverse push-up': 'Elevación de codo - flexión inversa',
  'elbow-to-knee': 'Codo a rodilla',
  'elevator': 'Elevador',
  'exercise ball alternating arm ups': 'Elevaciones alternas de brazos en balón de ejercicio',
  'exercise ball back extension with arms extended': 'Extensión de espalda en balón con brazos extendidos',
  'exercise ball back extension with hands behind head': 'Extensión de espalda en balón con manos detrás de la cabeza',
  'exercise ball back extension with knees off ground': 'Extensión de espalda en balón con rodillas despegadas del suelo',
  'exercise ball back extension with rotation': 'Extensión de espalda en balón con rotación',
  'exercise ball dip': 'Fondos en balón de ejercicio',
  'exercise ball hip flexor stretch': 'Estiramiento de flexores de cadera con balón',
  'exercise ball hug': 'Abrazo en balón de ejercicio',
  'exercise ball lat stretch': 'Estiramiento de dorsal con balón',
  'exercise ball lower back stretch (pyramid)': 'Estiramiento lumbar con balón (pirámide)',
  'exercise ball lying side lat stretch': 'Estiramiento lateral de dorsal acostado con balón',
  'exercise ball on the wall calf raise': 'Elevación de pantorrillas en balón contra la pared',
  'exercise ball on the wall calf raise (tennis ball between ankles)': 'Elevación de pantorrillas en balón contra la pared (pelota de tenis entre tobillos)',
  'exercise ball on the wall calf raise (tennis ball between knees)': 'Elevación de pantorrillas en balón contra la pared (pelota de tenis entre rodillas)',
  'exercise ball one leg prone lower body rotation': 'Rotación de tren inferior prono a una pierna en balón de ejercicio',
  'exercise ball one legged diagonal kick hamstring curl': 'Patada diagonal a una pierna con curl de isquiotibiales en balón de ejercicio',
  'exercise ball pike push up': 'Flexión de brazos en pica en balón de ejercicio',
  'exercise ball prone leg raise': 'Elevación de pierna prono en balón de ejercicio',
  'exercise ball seated hamstring stretch': 'Estiramiento de isquiotibiales sentado con balón',
  'exercise ball seated triceps stretch': 'Estiramiento de tríceps sentado con balón',
  'exercise ball supine triceps extension': 'Extensión de tríceps supino en balón de ejercicio',
  'ez bar french press on exercise ball': 'Press francés con barra EZ en balón de ejercicio',
  'ez bar lying bent arms pullover': 'Pullover con brazos flexionados acostado con barra EZ',
  'ez bar lying close grip triceps extension behind head': 'Extensión de tríceps agarre cerrado acostado por detrás de la cabeza con barra EZ',
  'ez bar reverse grip bent over row': 'Remo inclinado agarre inverso con barra EZ',
  'ez bar seated close grip concentration curl': 'Curl de concentración agarre cerrado sentado con barra EZ',
  'ez bar standing french press': 'Press francés de pie con barra EZ',
  'ez barbell anti gravity press': 'Press antigravedad con barra EZ',
  'ez barbell close grip preacher curl': 'Curl de predicador agarre cerrado con barra EZ',
  'ez barbell close-grip curl': 'Curl agarre cerrado con barra EZ',
  'ez barbell curl': 'Curl con barra EZ',
  'ez barbell decline close grip face press': 'Press de cara agarre cerrado declinado con barra EZ',
  'ez barbell decline triceps extension': 'Extensión de tríceps declinada con barra EZ',
  'ez barbell incline triceps extension': 'Extensión de tríceps inclinada con barra EZ',
  'ez barbell jm bench press': 'Press JM de banca con barra EZ',
  'ez barbell reverse grip curl': 'Curl agarre inverso con barra EZ',
  'ez barbell reverse grip preacher curl': 'Curl de predicador agarre inverso con barra EZ',
  'ez barbell seated curls': 'Curls sentados con barra EZ',
  'ez barbell seated triceps extension': 'Extensión de tríceps sentado con barra EZ',
  'ez barbell spider curl': 'Curl de araña con barra EZ',
  'ez-bar biceps curl (with arm blaster)': 'Curl de bíceps con barra EZ (con arm blaster)',
  'ez-bar close-grip bench press': 'Press de banca agarre cerrado con barra EZ',
  'ez-barbell standing wide grip biceps curl': 'Curl de bíceps agarre abierto de pie con barra EZ',
  'flag': 'Bandera',
  'flutter kicks': 'Patadas de aleteo',
  'forward jump': 'Salto hacia adelante',
  'forward lunge (male)': 'Zancada frontal',
  'frankenstein squat': 'Sentadilla Frankenstein',
  'frog crunch': 'Crunch de rana',
  'frog planche': 'Planche de rana',
  'front lever': 'Palanca anterior',
  'front lever reps': 'Repeticiones de palanca anterior',
  'front plank with twist': 'Plancha frontal con giro',
  'full maltese': 'Maltese completo',
  'full planche': 'Planche completo',
  'full planche push-up': 'Flexión de brazos en planche completo',
  'gironda sternum chin': 'Dominada esternón Gironda',
  'glute bridge march': 'Marcha de puente de glúteos',
  'glute bridge two legs on bench (male)': 'Puente de glúteos a dos piernas en banca',
  'glute-ham raise': 'Elevación de glúteo-isquiotibial',
  'gorilla chin': 'Dominada gorila',
  'groin crunch': 'Crunch de ingle',
  'hack calf raise': 'Elevación de pantorrillas hack',
  'hack one leg calf raise': 'Elevación de pantorrillas hack a una pierna',
  'hamstring stretch': 'Estiramiento de isquiotibiales',
  'hands bike': 'Bicicleta de manos',
  'hands clasped circular toe touch (male)': 'Toque circular de pies con manos entrelazadas',
  'hands reversed clasped circular toe touch (male)': 'Toque circular de pies con manos entrelazadas invertidas',
  'handstand': 'Parada de manos',
  'handstand push-up': 'Flexión de brazos en parada de manos',
  'hanging leg hip raise': 'Elevación de cadera con pierna colgando',
  'hanging leg raise': 'Elevación de pierna colgando',
  'hanging oblique knee raise': 'Elevación de rodilla oblicua colgando',
  'hanging pike': 'Pica colgando',
  'hanging straight leg hip raise': 'Elevación de cadera con pierna recta colgando',
  'hanging straight leg raise': 'Elevación de pierna recta colgando',
  'hanging straight twisting leg hip raise': 'Elevación de cadera con pierna recta giratoria colgando',
  'high knee against wall': 'Rodilla alta contra la pared',
  'hip raise (bent knee)': 'Elevación de cadera (rodillas flexionadas)',
  'hug keens to chest': 'Abrazar rodillas al pecho',
  'hyght dumbbell fly': 'Apertura Hyght con mancuerna',
  'impossible dips': 'Fondos imposibles',
  'inchworm': 'Gusano',
  'inchworm v. 2': 'Gusano v. 2',
  'incline close-grip push-up': 'Flexión de brazos inclinada agarre cerrado',
  'incline push up depth jump': 'Flexión de brazos inclinada con salto de profundidad',
  'incline push-up': 'Flexión de brazos inclinada',
  'incline push-up (on box)': 'Flexión de brazos inclinada (sobre caja)',
  'incline reverse grip push-up': 'Flexión de brazos inclinada agarre inverso',
  'incline scapula push up': 'Flexión de brazos inclinada escapular',
  'intermediate hip flexor and quad stretch': 'Estiramiento intermedio de flexores de cadera y cuádriceps',
  'inverted row': 'Remo invertido',
  'inverted row bent knees': 'Remo invertido con rodillas flexionadas',
  'inverted row on bench': 'Remo invertido en banca',
  'inverted row v. 2': 'Remo invertido v. 2',
  'inverted row with straps': 'Remo invertido con correas',
  'iron cross stretch': 'Estiramiento de cruz de hierro',
  'isometric chest squeeze': 'Compresión isométrica de pecho',
  'isometric wipers': 'Limpiaparabrisas isométrico',
  'jack jump (male)': 'Salto jack',
  'jackknife sit-up': 'Abdominal jackknife',
  'janda sit-up': 'Abdominal Janda',
  'jump rope': 'Saltar la cuerda',
  'jump squat': 'Sentadilla con salto',
  'jump squat v. 2': 'Sentadilla con salto v. 2',
  'kettlebell advanced windmill': 'Molino avanzado con kettlebell',
  'kettlebell alternating hang clean': 'Cargada alterna colgando con kettlebell',
  'kettlebell alternating press': 'Press alterno con kettlebell',
  'kettlebell alternating press on floor': 'Press alterno en suelo con kettlebell',
  'kettlebell alternating renegade row': 'Remo renegade alterno con kettlebell',
  'kettlebell alternating row': 'Remo alterno con kettlebell',
  'kettlebell arnold press': 'Press Arnold con kettlebell',
  'kettlebell bent press': 'Press inclinado con kettlebell',
  'kettlebell bottoms up clean from the hang position': 'Cargada de abajo hacia arriba desde posición colgante con kettlebell',
  'kettlebell double alternating hang clean': 'Cargada alterna colgante doble con kettlebell',
  'kettlebell double jerk': 'Jerk doble con kettlebell',
  'kettlebell double push press': 'Press de empuje doble con kettlebell',
  'kettlebell double snatch': 'Arrancada doble con kettlebell',
  'kettlebell double windmill': 'Molino doble con kettlebell',
  'kettlebell extended range one arm press on floor': 'Press a un brazo rango extendido en suelo con kettlebell',
  'kettlebell figure 8': 'Figura 8 con kettlebell',
  'kettlebell front squat': 'Sentadilla frontal con kettlebell',
  'kettlebell goblet squat': 'Sentadilla goblet con kettlebell',
  'kettlebell hang clean': 'Cargada colgando con kettlebell',
  'kettlebell lunge pass through': 'Zancada con paso de kettlebell',
  'kettlebell one arm clean and jerk': 'Cargada y jerk a un brazo con kettlebell',
  'kettlebell one arm floor press': 'Press a un brazo en suelo con kettlebell',
  'kettlebell one arm jerk': 'Jerk a un brazo con kettlebell',
  'kettlebell one arm military press to the side': 'Press militar a un brazo lateral con kettlebell',
  'kettlebell one arm push press': 'Press de empuje a un brazo con kettlebell',
  'kettlebell one arm row': 'Remo a un brazo con kettlebell',
  'kettlebell one arm snatch': 'Arrancada a un brazo con kettlebell',
  'kettlebell pirate supper legs': 'Piernas de pirata con kettlebell',
  'kettlebell pistol squat': 'Sentadilla pistola con kettlebell',
  'kettlebell plyo push-up': 'Flexión de brazos pliométrica con kettlebell',
  'kettlebell seated press': 'Press sentado con kettlebell',
  'kettlebell seated two arm military press': 'Press militar sentado a dos brazos con kettlebell',
  'kettlebell seesaw press': 'Press de balancín con kettlebell',
  'kettlebell sumo high pull': 'Jalón alto sumo con kettlebell',
  'kettlebell swing': 'Balanceo con kettlebell',
  'kettlebell thruster': 'Thruster con kettlebell',
  'kettlebell turkish get up (squat style)': 'Levantamiento turco (estilo sentadilla) con kettlebell',
  'kettlebell two arm clean': 'Cargada a dos brazos con kettlebell',
  'kettlebell two arm military press': 'Press militar a dos brazos con kettlebell',
  'kettlebell two arm row': 'Remo a dos brazos con kettlebell',
  'kettlebell windmill': 'Molino con kettlebell',
  'kick out sit': 'Abdominal con patada',
  'kipping muscle up': 'Muscle up con kip',
  'knee touch crunch': 'Crunch con toque de rodilla',
  'kneeling jump squat': 'Sentadilla con salto arrodillado',
  'kneeling lat stretch': 'Estiramiento de dorsal arrodillado',
  'korean dips': 'Fondos coreanos',
  'l-pull-up': 'Dominada en L',
  'lean planche': 'Planche inclinado',
  'left hook. boxing': 'Gancho izquierdo. Boxeo',
  'leg pull in flat bench': 'Jalón de pierna en banca plana',
  'leg up hamstring stretch': 'Estiramiento de isquiotibiales con pierna arriba',
  'lever alternate leg press': 'Press de piernas alterno en máquina palanca',
  'lever alternating narrow grip seated row': 'Remo sentado agarre estrecho alterno en máquina palanca',
  'lever assisted chin-up': 'Dominada agarre supino asistida en máquina palanca',
  'lever back extension': 'Extensión de espalda en máquina palanca',
  'lever bent over row': 'Remo inclinado en máquina palanca',
  'lever bent-over row with v-bar': 'Remo inclinado con V-barra en máquina palanca',
  'lever bicep curl': 'Curl de bíceps en máquina palanca',
  'lever calf press': 'Press de pantorrillas en máquina palanca',
  'lever chest press': 'Press de pecho en máquina palanca',
  'lever deadlift': 'Peso muerto en máquina palanca',
  'lever decline chest press': 'Press de pecho declinado en máquina palanca',
  'lever donkey calf raise': 'Elevación de pantorrillas tipo burro en máquina palanca',
  'lever front pulldown': 'Jalón frontal en máquina palanca',
  'lever gripless shrug': 'Encogimiento sin agarre en máquina palanca',
  'lever gripless shrug v. 2': 'Encogimiento sin agarre en máquina palanca v. 2',
  'lever gripper hands': 'Apretador de manos en máquina palanca',
  'lever hammer grip preacher curl': 'Curl de predicador agarre martillo en máquina palanca',
  'lever high row': 'Remo alto en máquina palanca',
  'lever hip extension v. 2': 'Extensión de cadera en máquina palanca v. 2',
  'lever horizontal one leg press': 'Press de piernas horizontal a una pierna en máquina palanca',
  'lever incline chest press': 'Press de pecho inclinado en máquina palanca',
  'lever incline chest press v. 2': 'Press de pecho inclinado en máquina palanca v. 2',
  'lever kneeling leg curl': 'Curl de pierna arrodillado en máquina palanca',
  'lever kneeling twist': 'Giro arrodillado en máquina palanca',
  'lever lateral raise': 'Elevación lateral en máquina palanca',
  'lever leg extension': 'Extensión de pierna en máquina palanca',
  'lever lying leg curl': 'Curl de pierna acostado en máquina palanca',
  'lever lying two-one leg curl': 'Curl de pierna acostado a dos-una pierna en máquina palanca',
  'lever military press': 'Press militar en máquina palanca',
  'lever narrow grip seated row': 'Remo sentado agarre estrecho en máquina palanca',
  'lever one arm bent over row': 'Remo a un brazo inclinado en máquina palanca',
  'lever one arm lateral high row': 'Remo alto lateral a un brazo en máquina palanca',
  'lever one arm lateral wide pulldown': 'Jalón lateral abierto a un brazo en máquina palanca',
  'lever one arm shoulder press': 'Press de hombro a un brazo en máquina palanca',
  'lever overhand triceps dip': 'Fondos de tríceps agarre prono en máquina palanca',
  'lever preacher curl': 'Curl de predicador en máquina palanca',
  'lever preacher curl v. 2': 'Curl de predicador en máquina palanca v. 2',
  'lever pullover': 'Pullover en máquina palanca',
  'lever reverse grip lateral pulldown': 'Jalón lateral agarre inverso en máquina palanca',
  'lever reverse grip preacher curl': 'Curl de predicador agarre inverso en máquina palanca',
  'lever reverse grip vertical row': 'Remo vertical agarre inverso en máquina palanca',
  'lever reverse hyperextension': 'Hiperextensión inversa en máquina palanca',
  'lever reverse t-bar row': 'Remo T-bar inverso en máquina palanca',
  'lever rotary calf': 'Pantorrilla rotativa en máquina palanca',
  'lever seated calf press': 'Press de pantorrillas sentado en máquina palanca',
  'lever seated calf raise': 'Elevación de pantorrillas sentado en máquina palanca',
  'lever seated crunch': 'Crunch sentado en máquina palanca',
  'lever seated crunch (chest pad)': 'Crunch sentado (apoyador de pecho) en máquina palanca',
  'lever seated crunch v. 2': 'Crunch sentado en máquina palanca v. 2',
  'lever seated dip': 'Fondos sentados en máquina palanca',
  'lever seated fly': 'Apertura sentado en máquina palanca',
  'lever seated good morning': 'Buenos días sentado en máquina palanca',
  'lever seated hip abduction': 'Abducción de cadera sentado en máquina palanca',
  'lever seated hip adduction': 'Aducción de cadera sentado en máquina palanca',
  'lever seated leg curl': 'Curl de pierna sentado en máquina palanca',
  'lever seated leg raise crunch': 'Crunch con elevación de pierna sentado en máquina palanca',
  'lever seated reverse fly': 'Apertura inversa sentado en máquina palanca',
  'lever seated reverse fly (parallel grip)': 'Apertura inversa sentado (agarre paralelo) en máquina palanca',
  'lever seated row': 'Remo sentado en máquina palanca',
  'lever seated squat calf raise on leg press machine': 'Elevación de pantorrillas sentado en sentadilla en máquina de press de piernas',
  'lever shoulder press': 'Press de hombro en máquina palanca',
  'lever shoulder press v. 2': 'Press de hombro en máquina palanca v. 2',
  'lever shoulder press v. 3': 'Press de hombro en máquina palanca v. 3',
  'lever shrug': 'Encogimiento en máquina palanca',
  'lever standing calf raise': 'Elevación de pantorrillas de pie en máquina palanca',
  'lever standing chest press': 'Press de pecho de pie en máquina palanca',
  'lever t bar row': 'Remo T-bar en máquina palanca',
  'lever t-bar reverse grip row': 'Remo T-bar agarre inverso en máquina palanca',
  'lever triceps extension': 'Extensión de tríceps en máquina palanca',
  'lever unilateral row': 'Remo unilateral en máquina palanca',
  'london bridge': 'Puente de Londres',
  'low glute bridge on floor': 'Puente de glúteos bajo en suelo',
  'lower back curl': 'Encogimiento de zona lumbar',
  'lunge with jump': 'Zancada con salto',
  'lunge with twist': 'Zancada con giro',
  'lying (side) quads stretch': 'Estiramiento de cuádriceps acostado (lateral)',
  'mixed grip chin-up': 'Dominada agarre supino mixto',
  'modified hindu push-up (male)': 'Flexión de brazos hindu modificada',
  'modified push up to lower arms': 'Flexión de brazos modificada a antebrazos',
  'monster walk': 'Caminata de monstruo',
  'muscle up': 'Muscle up',
  'muscle-up (on vertical bar)': 'Muscle up (en barra vertical)',
  'narrow push-up on exercise ball': 'Flexión de brazos estrecha en balón de ejercicio',
  'neck side stretch': 'Estiramiento lateral del cuello',
  'negative crunch': 'Crunch negativo',
  'oblique crunch v. 2': 'Crunch oblicuo v. 2',
  'oblique crunches floor': 'Crunches oblicuos en suelo',
  'one leg donkey calf raise': 'Elevación de pantorrillas tipo burro a una pierna',
  'one leg floor calf raise': 'Elevación de pantorrillas a una pierna en suelo',
  'otis up': 'Abdominal Otis',
  'outside leg kick push-up': 'Flexión de brazos con patada exterior de pierna',
  'overhead triceps stretch': 'Estiramiento de tríceps arriba',
  'pelvic tilt': 'Inclinación pélvica',
  'pelvic tilt into bridge': 'Inclinación pélvica a puente',
  'peroneals stretch': 'Estiramiento de peroneos',
  'plyo push up': 'Flexión de brazos pliométrica',
  'posterior step to overhead reach': 'Paso posterior con alcance arriba',
  'posterior tibialis stretch': 'Estiramiento de tibial posterior',
  'potty squat': 'Sentadilla tipo inodoro',
  'potty squat with support': 'Sentadilla tipo inodoro con apoyo',
  'power point plank': 'Plancha power point',
  'prisoner half sit-up (male)': 'Abdominal medio prisionero',
  'prone twist on stability ball': 'Giro prono en balón de estabilidad',
  'pull up (neutral grip)': 'Dominada (agarre neutro)',
  'pull-up': 'Dominada',
  'push and pull bodyweight': 'Empuje y tracción en peso corporal',
  'push to run': 'Empuje para correr',
  'push-up': 'Flexión de brazos',
  'push-up (bosu ball)': 'Flexión de brazos (bosu)',
  'push-up (on stability ball)': 'Flexión de brazos (sobre balón)',
  'push-up (wall)': 'Flexión de brazos (pared)',
  'push-up (wall) v. 2': 'Flexión de brazos (pared) v. 2',
  'push-up close-grip off dumbbell': 'Flexión de brazos agarre cerrado sobre mancuerna',
  'push-up inside leg kick': 'Flexión de brazos con patada interior de pierna',
  'push-up medicine ball': 'Flexión de brazos con balón medicinal',
  'push-up on lower arms': 'Flexión de brazos sobre antebrazos',
  'push-up plus': 'Flexión de brazos plus',
  'push-up to side plank': 'Flexión de brazos a plancha lateral',
  'quads': 'Cuádriceps',
  'quarter sit-up': 'Abdominal cuarto',
  'quick feet v. 2': 'Pies rápidos v. 2',
  'raise single arm push-up': 'Flexión de brazos a una mano elevada',
  'rear deltoid stretch': 'Estiramiento de deltoides posterior',
  'rear pull-up': 'Dominada posterior',
  'reclining big toe pose with rope': 'Postura de dedo gordo reclinado con cuerda',
  'resistance band hip thrusts on knees (female)': 'Empujes de cadera en rodillas con banda de resistencia',
  'resistance band leg extension': 'Extensión de pierna con banda de resistencia',
  'resistance band seated biceps curl': 'Curl de bíceps sentado con banda de resistencia',
  'resistance band seated chest press': 'Press de pecho sentado con banda de resistencia',
  'resistance band seated hip abduction': 'Abducción de cadera sentado con banda de resistencia',
  'resistance band seated shoulder press': 'Press de hombro sentado con banda de resistencia',
  'resistance band seated straight back row': 'Remo espalda recta sentado con banda de resistencia',
  'reverse crunch': 'Crunch inverso',
  'reverse dip': 'Fondos inversos',
  'reverse grip pull-up': 'Dominada agarre inverso',
  'reverse plank with leg lift': 'Plancha inversa con elevación de pierna',
  'ring dips': 'Fondos en anillas',
  'rocking frog stretch': 'Estiramiento de rana con balanceo',
  'rocky pull-up pulldown': 'Dominada jalón Rocky',
  'roller back stretch': 'Estiramiento de espalda con rodillo',
  'roller body saw': 'Sierra corporal con rodillo',
  'roller hip lat stretch': 'Estiramiento de cadera y dorsal con rodillo',
  'roller hip stretch': 'Estiramiento de cadera con rodillo',
  'roller reverse crunch': 'Crunch inverso con rodillo',
  'roller side lat stretch': 'Estiramiento lateral de dorsal con rodillo',
  'rope climb': 'Trepar cuerda',
  'run': 'Correr',
  'run (equipment)': 'Correr (con equipo)',
  'runners stretch': 'Estiramiento de corredor',
  'russian twist': 'Giro ruso',
  'scapula dips': 'Fondos escapulares',
  'scapular pull-up': 'Dominada escapular',
  'scissor jumps (male)': 'Saltos de tijera',
  'seated glute stretch': 'Estiramiento de glúteos sentado',
  'seated leg raise': 'Elevación de pierna sentado',
  'seated lower back stretch': 'Estiramiento lumbar sentado',
  'seated piriformis stretch': 'Estiramiento de piriforme sentado',
  'seated side crunch (wall)': 'Crunch lateral sentado (pared)',
  'seated wide angle pose sequence': 'Secuencia de postura de ángulo abierto sentado',
  'semi squat jump (male)': 'Salto en semisentadilla',
  'short stride run': 'Carrera de zancada corta',
  'shoulder grip pull-up': 'Dominada agarre de hombro',
  'side bridge hip abduction': 'Puente lateral con abducción de cadera',
  'side bridge v. 2': 'Puente lateral v. 2',
  'side hip (on parallel bars)': 'Cadera lateral (en barras paralelas)',
  'side hip abduction': 'Abducción de cadera lateral',
  'side lying floor stretch': 'Estiramiento acostado lateral en suelo',
  'side lying hip adduction (male)': 'Aducción de cadera acostado lateral',
  'side plank hip adduction': 'Plancha lateral con aducción de cadera',
  'side push neck stretch': 'Estiramiento de cuello con empuje lateral',
  'side wrist pull stretch': 'Estiramiento de muñeca con tracción lateral',
  'single arm push-up': 'Flexión de brazos a una mano',
  'sissy squat': 'Sentadilla sissy',
  'sit-up v. 2': 'Abdominal v. 2',
  'sit-up with arms on chest': 'Abdominal con brazos en el pecho',
  'ski ergometer': 'Ergómetro de esquí',
  'ski step': 'Paso de esquí',
  'skin the cat': 'Skin the cat',
  'sled 45 degrees one leg press': 'Press de piernas a 45 grados a una pierna en trineo',
  'sled 45° leg press (side pov)': 'Press de piernas a 45° en trineo (vista lateral)',
  'sled 45в° calf press': 'Press de pantorrillas a 45° en trineo',
  'sled 45в° leg press': 'Press de piernas a 45° en trineo',
  'sled 45в° leg press (back pov)': 'Press de piernas a 45° en trineo (vista trasera)',
  'sled 45в° leg wide press': 'Press de piernas abierto a 45° en trineo',
  'sled calf press on leg press': 'Press de pantorrillas en press de piernas en trineo',
  'sled closer hack squat': 'Sentadilla hack cerrada en trineo',
  'sled forward angled calf raise': 'Elevación de pantorrillas inclinada hacia adelante en trineo',
  'sled hack squat': 'Sentadilla hack en trineo',
  'sled lying calf press': 'Press de pantorrillas acostado en trineo',
  'sled lying squat': 'Sentadilla acostado en trineo',
  'sled one leg calf press on leg press': 'Press de pantorrillas a una pierna en press de piernas en trineo',
  'sledge hammer': 'Martillo de albañil',
  'smith back shrug': 'Encogimiento de espalda en Smith',
  'smith behind neck press': 'Press por detrás del cuello en Smith',
  'smith bench press': 'Press de banca en Smith',
  'smith bent knee good morning': 'Buenos días con rodilla flexionada en Smith',
  'smith bent over row': 'Remo inclinado en Smith',
  'smith chair squat': 'Sentadilla silla en Smith',
  'smith close-grip bench press': 'Press de banca agarre cerrado en Smith',
  'smith deadlift': 'Peso muerto en Smith',
  'smith decline bench press': 'Press de banca declinado en Smith',
  'smith front squat (clean grip)': 'Sentadilla frontal (agarre de cargada) en Smith',
  'smith full squat': 'Sentadilla completa en Smith',
  'smith hack squat': 'Sentadilla hack en Smith',
  'smith hip raise': 'Elevación de cadera en Smith',
  'smith incline bench press': 'Press de banca inclinado en Smith',
  'smith incline reverse-grip press': 'Press inclinado agarre inverso en Smith',
  'smith incline shoulder raises': 'Elevaciones de hombro inclinadas en Smith',
  'smith leg press': 'Press de piernas en Smith',
  'smith low bar squat': 'Sentadilla barra baja en Smith',
  'smith machine bicep curl': 'Curl de bíceps en máquina Smith',
  'smith machine decline close grip bench press': 'Press de banca declinado agarre cerrado en máquina Smith',
  'smith machine incline tricep extension': 'Extensión de tríceps inclinada en máquina Smith',
  'smith machine reverse decline close grip bench press': 'Press de banca declinado inverso agarre cerrado en máquina Smith',
  'smith narrow row': 'Remo estrecho en Smith',
  'smith one arm row': 'Remo a un brazo en Smith',
  'smith rear delt row': 'Remo de deltoides posterior en Smith',
  'smith reverse calf raises': 'Elevaciones de pantorrillas inversas en Smith',
  'smith reverse grip bent over row': 'Remo inclinado agarre inverso en Smith',
  'smith reverse-grip press': 'Press agarre inverso en Smith',
  'smith seated one leg calf raise': 'Elevación de pantorrillas a una pierna sentado en Smith',
  'smith seated shoulder press': 'Press de hombro sentado en Smith',
  'smith seated wrist curl': 'Curl de muñeca sentado en Smith',
  'smith shoulder press': 'Press de hombro en Smith',
  'smith shrug': 'Encogimiento en Smith',
  'smith single leg split squat': 'Sentadilla dividida a una pierna en Smith',
  'smith sprint lunge': 'Zancada de sprint en Smith',
  'smith squat': 'Sentadilla en Smith',
  'smith standing back wrist curl': 'Curl de muñeca de pie por detrás en Smith',
  'smith standing behind head military press': 'Press militar de pie por detrás de la cabeza en Smith',
  'smith standing leg calf raise': 'Elevación de pantorrillas de pie con pierna en Smith',
  'smith standing military press': 'Press militar de pie en Smith',
  'smith sumo squat': 'Sentadilla sumo en Smith',
  'smith toe raise': 'Elevación de dedos del pie en Smith',
  'smith upright row': 'Remo al mentón en Smith',
  'smith wide grip bench press': 'Press de banca agarre abierto en Smith',
  'smith wide grip decline bench press': 'Press de banca declinado agarre abierto en Smith',
  'spell caster': 'Lanzador de hechizos',
  'spider crawl push up': 'Flexión de brazos de araña',
  'spine stretch': 'Estiramiento de columna',
  'spine twist': 'Giro de columna',
  'squat on bosu ball': 'Sentadilla en bosu',
  'squat to overhead reach': 'Sentadilla con alcance arriba',
  'squat to overhead reach with twist': 'Sentadilla con alcance arriba y giro',
  'stalder press': 'Press Stalder',
  'standing archer': 'Arquero de pie',
  'standing calf raise (on a staircase)': 'Elevación de pantorrillas de pie (en escalera)',
  'standing calves': 'Pantorrillas de pie',
  'standing calves calf stretch': 'Estiramiento de pantorrillas de pie',
  'standing hamstring and calf stretch with strap': 'Estiramiento de isquiotibiales y pantorrillas de pie con correa',
  'standing lateral stretch': 'Estiramiento lateral de pie',
  'standing pelvic tilt': 'Inclinación pélvica de pie',
  'standing single leg curl': 'Curl a una pierna de pie',
  'standing wheel rollerout': 'Rodamiento de rueda de pie',
  'star jump (male)': 'Salto estrella',
  'stationary bike run v. 3': 'Carrera en bicicleta estática v. 3',
  'stationary bike walk': 'Caminata en bicicleta estática',
  'straddle maltese': 'Maltese con piernas abiertas',
  'straddle planche': 'Planche con piernas abiertas',
  'straight leg outer hip abductor': 'Abductor de cadera externo con pierna recta',
  'superman push-up': 'Flexión de brazos superman',
  'suspended abdominal fallout': 'Caída abdominal suspendido',
  'suspended push-up': 'Flexión de brazos suspendida',
  'suspended reverse crunch': 'Crunch inverso suspendido',
  'suspended row': 'Remo suspendido',
  'suspended split squat': 'Sentadilla dividida suspendida',
  'swing 360': 'Balanceo 360',
  'three bench dip': 'Tres fondos de banca',
  'tire flip': 'Volteo de llanta',
  'trap bar deadlift': 'Peso muerto con barra hexagonal',
  'triceps dip': 'Fondos de tríceps',
  'triceps dip (bench leg)': 'Fondos de tríceps (piernas en banca)',
  'triceps dip (between benches)': 'Fondos de tríceps (entre bancas)',
  'triceps dips floor': 'Fondos de tríceps en suelo',
  'tuck crunch': 'Crunch tuck',
  'twist hip lift': 'Elevación de cadera con giro',
  'twisted leg raise': 'Elevación de pierna girada',
  'twisted leg raise (female)': 'Elevación de pierna girada',
  'upper back stretch': 'Estiramiento de espalda alta',
  'v-sit on floor': 'V-sit en suelo',
  'walk elliptical cross trainer': 'Caminata en elíptica',
  'walking high knees lunge': 'Zancada caminando con rodillas altas',
  'walking lunge': 'Zancada caminando',
  'walking on incline treadmill': 'Caminata en cinta inclinada',
  'walking on stepmill': 'Caminata en stepmill',
  'weighted bench dip': 'Fondos de banca con peso',
  'weighted close grip chin-up on dip cage': 'Dominada agarre supino cerrado con peso en jaula de fondos',
  'weighted cossack squats (male)': 'Sentadillas cosacas con peso',
  'weighted crunch': 'Crunch con peso',
  'weighted decline sit-up': 'Abdominal declinado con peso',
  'weighted donkey calf raise': 'Elevación de pantorrillas tipo burro con peso',
  'weighted drop push up': 'Flexión de brazos con caída y peso',
  'weighted front plank': 'Plancha frontal con peso',
  'weighted front raise': 'Elevación frontal con peso',
  'weighted hanging leg-hip raise': 'Elevación de cadera con pierna colgando con peso',
  'weighted hyperextension (on stability ball)': 'Hiperextensión con peso (en balón de estabilidad)',
  'weighted kneeling step with swing': 'Paso arrodillado con balanceo y peso',
  'weighted lunge with swing': 'Zancada con balanceo y peso',
  'weighted muscle up': 'Muscle up con peso',
  'weighted muscle up (on bar)': 'Muscle up con peso (en barra)',
  'weighted one hand pull up': 'Dominada a una mano con peso',
  'weighted overhead crunch (on stability ball)': 'Crunch arriba con peso (en balón de estabilidad)',
  'weighted pull-up': 'Dominada con peso',
  'weighted round arm': 'Brazo redondo con peso',
  'weighted russian twist': 'Giro ruso con peso',
  'weighted russian twist (legs up)': 'Giro ruso con peso (piernas arriba)',
  'weighted russian twist v. 2': 'Giro ruso con peso v. 2',
  'weighted seated bicep curl (on stability ball)': 'Curl de bíceps sentado con peso (en balón de estabilidad)',
  'weighted seated twist (on stability ball)': 'Giro sentado con peso (en balón de estabilidad)',
  'weighted side bend (on stability ball)': 'Flexión lateral con peso (en balón de estabilidad)',
  'weighted sissy squat': 'Sentadilla sissy con peso',
  'weighted squat': 'Sentadilla con peso',
  'weighted standing curl': 'Curl de pie con peso',
  'weighted standing hand squeeze': 'Compresión de mano de pie con peso',
  'weighted straight bar dip': 'Fondos en barra recta con peso',
  'weighted stretch lunge': 'Zancada de estiramiento con peso',
  'weighted svend press': 'Press Svend con peso',
  'weighted three bench dips': 'Tres fondos de banca con peso',
  'weighted tricep dips': 'Fondos de tríceps con peso',
  'weighted triceps dip on high parallel bars': 'Fondos de tríceps en barras paralelas altas con peso',
  'wheel rollerout': 'Rodamiento de rueda',
  'wheel run': 'Carrera de rueda',
  'wide grip pull-up': 'Dominada agarre abierto',
  'wide grip rear pull-up': 'Dominada posterior agarre abierto',
  'wide hand push up': 'Flexión de brazos manos abiertas',
  'wind sprints': 'Sprints de viento',
  'world greatest stretch': 'El mejor estiramiento del mundo',
  'wrist circles': 'Círculos de muñeca',
};

// Total translations: 1211