export interface SeedExercise {
  name: string;
  category: 'Strength' | 'Cardio' | 'Flexibility' | 'HIIT';
  muscleGroup: string;
  description: string;
}

export const SEED_EXERCISES: SeedExercise[] = [
  // ─── STRENGTH: CHEST ────────────────────────────────────────────────
  { name: 'Barbell Bench Press', category: 'Strength', muscleGroup: 'Chest', description: 'Lie on a flat bench and press a barbell upward from chest level to full arm extension.' },
  { name: 'Incline Barbell Bench Press', category: 'Strength', muscleGroup: 'Chest', description: 'Press a barbell upward while lying on an inclined bench to target the upper chest.' },
  { name: 'Decline Barbell Bench Press', category: 'Strength', muscleGroup: 'Chest', description: 'Press a barbell upward while lying on a declined bench to target the lower chest.' },
  { name: 'Dumbbell Bench Press', category: 'Strength', muscleGroup: 'Chest', description: 'Lie on a flat bench and press two dumbbells upward from chest level.' },
  { name: 'Incline Dumbbell Bench Press', category: 'Strength', muscleGroup: 'Chest', description: 'Press dumbbells upward on an inclined bench for upper chest emphasis.' },
  { name: 'Decline Dumbbell Bench Press', category: 'Strength', muscleGroup: 'Chest', description: 'Press dumbbells upward on a declined bench for lower chest emphasis.' },
  { name: 'Dumbbell Flyes', category: 'Strength', muscleGroup: 'Chest', description: 'Lie on a flat bench and open your arms wide with dumbbells, then bring them together.' },
  { name: 'Incline Dumbbell Flyes', category: 'Strength', muscleGroup: 'Chest', description: 'Perform dumbbell flyes on an inclined bench to target the upper chest.' },
  { name: 'Cable Crossover (High)', category: 'Strength', muscleGroup: 'Chest', description: 'Pull high cable handles downward and together in front of your chest.' },
  { name: 'Cable Crossover (Low)', category: 'Strength', muscleGroup: 'Chest', description: 'Pull low cable handles upward and together in front of your chest.' },
  { name: 'Cable Crossover (Middle)', category: 'Strength', muscleGroup: 'Chest', description: 'Pull mid-level cable handles together in front of your chest at nipple height.' },
  { name: 'Push-ups', category: 'Strength', muscleGroup: 'Chest', description: 'Lower and raise your body using your arms while maintaining a straight plank position.' },
  { name: 'Incline Push-ups', category: 'Strength', muscleGroup: 'Chest', description: 'Perform push-ups with hands elevated on a bench or step for reduced difficulty.' },
  { name: 'Decline Push-ups', category: 'Strength', muscleGroup: 'Chest', description: 'Perform push-ups with feet elevated on a bench for increased upper chest activation.' },
  { name: 'Diamond Push-ups', category: 'Strength', muscleGroup: 'Chest', description: 'Perform push-ups with hands close together forming a diamond shape under the chest.' },
  { name: 'Wide-Grip Push-ups', category: 'Strength', muscleGroup: 'Chest', description: 'Perform push-ups with hands placed wider than shoulder-width to emphasize the chest.' },
  { name: 'Chest Dips', category: 'Strength', muscleGroup: 'Chest', description: 'Lower your body between parallel bars while leaning forward to target the chest.' },
  { name: 'Chest Press Machine', category: 'Strength', muscleGroup: 'Chest', description: 'Push the handles of a seated machine forward from chest level in a controlled motion.' },
  { name: 'Pec Deck Machine', category: 'Strength', muscleGroup: 'Chest', description: 'Bring the padded arms of the machine together in front of your chest in an arc motion.' },
  { name: 'Cable Chest Fly', category: 'Strength', muscleGroup: 'Chest', description: 'Perform a standing fly motion using cable pulleys for constant tension on the chest.' },

  // ─── STRENGTH: BACK ─────────────────────────────────────────────────
  { name: 'Conventional Deadlift', category: 'Strength', muscleGroup: 'Back', description: 'Lift a barbell from the floor to hip height by extending your hips and knees simultaneously.' },
  { name: 'Romanian Deadlift', category: 'Strength', muscleGroup: 'Back', description: 'Lower a barbell along your legs by hinging at the hips while keeping a slight knee bend.' },
  { name: 'Sumo Deadlift', category: 'Strength', muscleGroup: 'Back', description: 'Lift a barbell from the floor with a wide stance and hands inside the knees.' },
  { name: 'Wide-Grip Pull-ups', category: 'Strength', muscleGroup: 'Back', description: 'Pull your chin above a wide-grip bar to develop the outer lats.' },
  { name: 'Close-Grip Pull-ups', category: 'Strength', muscleGroup: 'Back', description: 'Pull your chin above a narrow-grip bar with palms facing you for lat and bicep emphasis.' },
  { name: 'Neutral-Grip Pull-ups', category: 'Strength', muscleGroup: 'Back', description: 'Pull your chin above a bar with palms facing each other for a balanced back workout.' },
  { name: 'Chin-ups', category: 'Strength', muscleGroup: 'Back', description: 'Pull your chin above a supinated-grip bar, emphasizing biceps alongside the lats.' },
  { name: 'Bent-Over Barbell Row', category: 'Strength', muscleGroup: 'Back', description: 'Row a barbell toward your lower chest while bent at the hips with a flat back.' },
  { name: 'Pendlay Row', category: 'Strength', muscleGroup: 'Back', description: 'Explosively row a barbell from the floor to your chest with each rep returning to the ground.' },
  { name: 'One-Arm Dumbbell Row', category: 'Strength', muscleGroup: 'Back', description: 'Row a dumbbell toward your hip while supporting yourself on a bench with the opposite hand.' },
  { name: 'Lat Pulldown', category: 'Strength', muscleGroup: 'Back', description: 'Pull a cable bar down to your upper chest while seated at a lat pulldown machine.' },
  { name: 'Seated Cable Row', category: 'Strength', muscleGroup: 'Back', description: 'Pull a cable attachment toward your midsection while seated with legs braced.' },
  { name: 'T-Bar Row', category: 'Strength', muscleGroup: 'Back', description: 'Row a T-bar toward your chest while bent over with a stable, flat back position.' },
  { name: 'Face Pulls', category: 'Strength', muscleGroup: 'Back', description: 'Pull a rope attachment toward your face, squeezing the rear delts and upper back.' },
  { name: 'Hyperextensions', category: 'Strength', muscleGroup: 'Back', description: 'Lower and raise your torso on a hyperextension bench to strengthen the lower back.' },
  { name: 'Good Mornings', category: 'Strength', muscleGroup: 'Back', description: 'Hinge at the hips with a barbell on your back to strengthen the posterior chain.' },
  { name: 'Rack Pulls', category: 'Strength', muscleGroup: 'Back', description: 'Pull a barbell from knee-height pins in a power rack to overload the upper deadlift range.' },
  { name: 'Straight-Arm Pulldown', category: 'Strength', muscleGroup: 'Back', description: 'Pull a straight bar from overhead to your thighs with locked arms to isolate the lats.' },
  { name: 'Chest-Supported Dumbbell Row', category: 'Strength', muscleGroup: 'Back', description: 'Row dumbbells while lying face-down on an inclined bench to eliminate momentum.' },
  { name: 'Meadows Row', category: 'Strength', muscleGroup: 'Back', description: 'Row a landmine bar from a bent-over position with a neutral grip for upper back thickness.' },

  // ─── STRENGTH: SHOULDERS ────────────────────────────────────────────
  { name: 'Barbell Overhead Press', category: 'Strength', muscleGroup: 'Shoulders', description: 'Press a barbell from shoulder height to overhead while standing upright.' },
  { name: 'Dumbbell Overhead Press', category: 'Strength', muscleGroup: 'Shoulders', description: 'Press two dumbbells from shoulder height to overhead while standing or seated.' },
  { name: 'Seated Dumbbell Press', category: 'Strength', muscleGroup: 'Shoulders', description: 'Press dumbbells overhead while seated for stable shoulder development.' },
  { name: 'Arnold Press', category: 'Strength', muscleGroup: 'Shoulders', description: 'Press dumbbells overhead while rotating the palms from facing you to facing forward.' },
  { name: 'Dumbbell Lateral Raises', category: 'Strength', muscleGroup: 'Shoulders', description: 'Raise dumbbells out to the sides until arms are parallel to the floor.' },
  { name: 'Cable Lateral Raises', category: 'Strength', muscleGroup: 'Shoulders', description: 'Raise a low cable out to the side to isolate the lateral deltoid.' },
  { name: 'Dumbbell Front Raises', category: 'Strength', muscleGroup: 'Shoulders', description: 'Raise a dumbbell in front of you to shoulder height with a straight arm.' },
  { name: 'Cable Front Raises', category: 'Strength', muscleGroup: 'Shoulders', description: 'Raise a low cable in front of you to target the anterior deltoid.' },
  { name: 'Reverse Dumbbell Flyes', category: 'Strength', muscleGroup: 'Shoulders', description: 'Bend forward and raise dumbbells out to the sides to target the rear delts.' },
  { name: 'Reverse Pec Deck', category: 'Strength', muscleGroup: 'Shoulders', description: 'Push the arms of a pec deck machine outward behind you to work the rear delts.' },
  { name: 'Barbell Upright Rows', category: 'Strength', muscleGroup: 'Shoulders', description: 'Pull a barbell vertically along your body to chest height with elbows leading.' },
  { name: 'Dumbbell Upright Rows', category: 'Strength', muscleGroup: 'Shoulders', description: 'Pull dumbbells vertically along your body to chest height with elbows leading.' },
  { name: 'Barbell Shrugs', category: 'Strength', muscleGroup: 'Shoulders', description: 'Elevate your shoulders toward your ears while holding a barbell with straight arms.' },
  { name: 'Dumbbell Shrugs', category: 'Strength', muscleGroup: 'Shoulders', description: 'Elevate your shoulders toward your ears while holding dumbbells with straight arms.' },
  { name: 'Cable Shrugs', category: 'Strength', muscleGroup: 'Shoulders', description: 'Elevate your shoulders toward your ears while holding cable handles with straight arms.' },
  { name: 'Lu Raise', category: 'Strength', muscleGroup: 'Shoulders', description: 'Raise dumbbells from your sides to overhead in a controlled circular motion.' },
  { name: 'Landmine Press', category: 'Strength', muscleGroup: 'Shoulders', description: 'Press a landmine bar upward at an angle from one shoulder for shoulder and core stability.' },
  { name: 'Bus Drivers', category: 'Strength', muscleGroup: 'Shoulders', description: 'Hold a weight plate in front of you and rotate it like a steering wheel for shoulder endurance.' },

  // ─── STRENGTH: BICEPS ───────────────────────────────────────────────
  { name: 'Barbell Curl', category: 'Strength', muscleGroup: 'Biceps', description: 'Curl a barbell from your thighs to your chest while keeping your elbows at your sides.' },
  { name: 'EZ-Bar Curl', category: 'Strength', muscleGroup: 'Biceps', description: 'Curl an EZ-bar with a semi-supinated grip to reduce wrist strain while building the biceps.' },
  { name: 'Standing Dumbbell Curl', category: 'Strength', muscleGroup: 'Biceps', description: 'Curl dumbbells alternately from your sides to shoulder height with controlled form.' },
  { name: 'Seated Dumbbell Curl', category: 'Strength', muscleGroup: 'Biceps', description: 'Curl dumbbells while seated to isolate the biceps and reduce momentum.' },
  { name: 'Incline Dumbbell Curl', category: 'Strength', muscleGroup: 'Biceps', description: 'Curl dumbbells while seated on an inclined bench to emphasize the long head of the bicep.' },
  { name: 'Hammer Curl', category: 'Strength', muscleGroup: 'Biceps', description: 'Curl dumbbells with a neutral grip to target the brachialis and brachioradialis.' },
  { name: 'Preacher Curl', category: 'Strength', muscleGroup: 'Biceps', description: 'Curl a barbell or dumbbell on a preacher bench to isolate the biceps peak.' },
  { name: 'Cable Curl', category: 'Strength', muscleGroup: 'Biceps', description: 'Curl a cable attachment from a low pulley to maintain constant tension on the biceps.' },
  { name: 'Concentration Curl', category: 'Strength', muscleGroup: 'Biceps', description: 'Curl a dumbbell while seated with your elbow braced against your inner thigh.' },
  { name: 'Spider Curl', category: 'Strength', muscleGroup: 'Biceps', description: 'Curl a barbell or dumbbells while lying face-down on an inclined bench for peak contraction.' },
  { name: 'Cable Hammer Curl', category: 'Strength', muscleGroup: 'Biceps', description: 'Curl a rope attachment on a cable machine with a neutral grip for brachialis emphasis.' },

  // ─── STRENGTH: TRICEPS ──────────────────────────────────────────────
  { name: 'Tricep Rope Pushdown', category: 'Strength', muscleGroup: 'Triceps', description: 'Push a rope attachment downward on a cable machine, spreading the ends at the bottom.' },
  { name: 'Tricep Bar Pushdown', category: 'Strength', muscleGroup: 'Triceps', description: 'Push a straight or V-bar downward on a cable machine to target the triceps.' },
  { name: 'Skull Crushers', category: 'Strength', muscleGroup: 'Triceps', description: 'Lower an EZ-bar toward your forehead while lying on a bench, then extend back up.' },
  { name: 'Overhead Dumbbell Tricep Extension', category: 'Strength', muscleGroup: 'Triceps', description: 'Hold a dumbbell overhead with both hands and lower it behind your head, then extend.' },
  { name: 'Overhead Cable Tricep Extension', category: 'Strength', muscleGroup: 'Triceps', description: 'Extend a cable overhead from behind your head to fully contract the triceps.' },
  { name: 'Close-Grip Bench Press', category: 'Strength', muscleGroup: 'Triceps', description: 'Press a barbell with hands shoulder-width apart to emphasize the triceps over the chest.' },
  { name: 'Tricep Dips', category: 'Strength', muscleGroup: 'Triceps', description: 'Lower your body between parallel bars with an upright torso to emphasize the triceps.' },
  { name: 'Dumbbell Tricep Kickbacks', category: 'Strength', muscleGroup: 'Triceps', description: 'Extend a dumbbell backward from a bent-over position, locking out the elbow.' },
  { name: 'Bench Dips', category: 'Strength', muscleGroup: 'Triceps', description: 'Lower your body using a bench behind you with feet on the floor to work the triceps.' },
  { name: 'JM Press', category: 'Strength', muscleGroup: 'Triceps', description: 'Lower a barbell toward your upper chest with a hybrid bench press and skull crusher motion.' },
  { name: 'Overhead Barbell Extension', category: 'Strength', muscleGroup: 'Triceps', description: 'Lower a barbell behind your head and extend upward to isolate the long head of the triceps.' },

  // ─── STRENGTH: LEGS — QUADS ─────────────────────────────────────────
  { name: 'Barbell Back Squat', category: 'Strength', muscleGroup: 'Legs', description: 'Squat down with a barbell across your upper back, then drive through your heels to stand.' },
  { name: 'Barbell Front Squat', category: 'Strength', muscleGroup: 'Legs', description: 'Squat down with a barbell racked across your front deltoids for quad emphasis.' },
  { name: 'Goblet Squat', category: 'Strength', muscleGroup: 'Legs', description: 'Squat down while holding a dumbbell or kettlebell at chest level to teach proper form.' },
  { name: 'Leg Press', category: 'Strength', muscleGroup: 'Legs', description: 'Push a weighted platform away from you with your feet on a leg press machine.' },
  { name: 'Walking Lunges', category: 'Strength', muscleGroup: 'Legs', description: 'Step forward into alternating lunges while walking to work each leg independently.' },
  { name: 'Reverse Lunges', category: 'Strength', muscleGroup: 'Legs', description: 'Step backward into alternating lunges to reduce knee stress while building the quads.' },
  { name: 'Forward Lunges', category: 'Strength', muscleGroup: 'Legs', description: 'Step forward into alternating lunges with dumbbells or a barbell for quad development.' },
  { name: 'Barbell Lunges', category: 'Strength', muscleGroup: 'Legs', description: 'Perform lunges with a barbell across your upper back for added resistance.' },
  { name: 'Leg Extensions', category: 'Strength', muscleGroup: 'Legs', description: 'Extend your legs against resistance on a machine to isolate the quadriceps.' },
  { name: 'Bulgarian Split Squat', category: 'Strength', muscleGroup: 'Legs', description: 'Perform a single-leg squat with your rear foot elevated on a bench.' },
  { name: 'Step-ups', category: 'Strength', muscleGroup: 'Legs', description: 'Step onto a box or bench with one leg, driving through the heel to stand fully.' },
  { name: 'Wall Sit', category: 'Strength', muscleGroup: 'Legs', description: 'Hold a seated position against a wall with thighs parallel to the floor for isometric quad work.' },
  { name: 'Sissy Squat', category: 'Strength', muscleGroup: 'Legs', description: 'Lean back while bending your knees to deeply stretch and strengthen the quadriceps.' },
  { name: 'Hack Squat', category: 'Strength', muscleGroup: 'Legs', description: 'Squat on a machine with shoulder pads, pushing the weight through your legs.' },
  { name: 'Pistol Squat', category: 'Strength', muscleGroup: 'Legs', description: 'Squat down on one leg while extending the other leg forward for advanced quad strength.' },
  { name: 'Lateral Lunges', category: 'Strength', muscleGroup: 'Legs', description: 'Step to the side and lunge laterally to work the quads, glutes, and inner thighs.' },
  { name: 'Terminal Knee Extension', category: 'Strength', muscleGroup: 'Legs', description: 'Attach a band behind your knee and fully extend the leg to isolate the VMO.' },

  // ─── STRENGTH: LEGS — HAMSTRINGS ────────────────────────────────────
  { name: 'Lying Leg Curl', category: 'Strength', muscleGroup: 'Legs', description: 'Curl your legs toward your glutes on a machine while lying face-down.' },
  { name: 'Seated Leg Curl', category: 'Strength', muscleGroup: 'Legs', description: 'Curl your legs under the seat on a seated leg curl machine to isolate the hamstrings.' },
  { name: 'Nordic Hamstring Curl', category: 'Strength', muscleGroup: 'Legs', description: 'Lower your body toward the floor from a kneeling position, controlling the descent with your hamstrings.' },
  { name: 'Glute Ham Raise', category: 'Strength', muscleGroup: 'Legs', description: 'Raise and lower your torso on a GHD machine using your hamstrings and glutes.' },
  { name: 'Stiff-Leg Deadlift', category: 'Strength', muscleGroup: 'Legs', description: 'Lower a barbell along your legs with nearly straight knees to stretch and strengthen the hamstrings.' },
  { name: 'Single-Leg Romanian Deadlift', category: 'Strength', muscleGroup: 'Legs', description: 'Hinge at the hip on one leg while lowering a dumbbell toward the floor for balance and hamstring strength.' },
  { name: 'Cable Leg Curl', category: 'Strength', muscleGroup: 'Legs', description: 'Attach a cable to your ankle and curl toward your glutes for isolated hamstring work.' },

  // ─── STRENGTH: LEGS — GLUTES ────────────────────────────────────────
  { name: 'Barbell Hip Thrust', category: 'Strength', muscleGroup: 'Legs', description: 'Drive your hips upward with a barbell across your lap while your back rests on a bench.' },
  { name: 'Dumbbell Hip Thrust', category: 'Strength', muscleGroup: 'Legs', description: 'Drive your hips upward with a dumbbell across your lap while your back rests on a bench.' },
  { name: 'Glute Bridge', category: 'Strength', muscleGroup: 'Legs', description: 'Lie on your back and drive your hips upward, squeezing your glutes at the top.' },
  { name: 'Single-Leg Glute Bridge', category: 'Strength', muscleGroup: 'Legs', description: 'Perform a glute bridge on one leg for unilateral glute activation and stability.' },
  { name: 'Cable Pull-Through', category: 'Strength', muscleGroup: 'Legs', description: 'Pull a rope between your legs from a low cable, thrusting your hips forward to engage the glutes.' },
  { name: 'Sumo Squat', category: 'Strength', muscleGroup: 'Legs', description: 'Squat with a wide stance and toes turned out to emphasize the glutes and inner thighs.' },
  { name: 'Cable Hip Abduction', category: 'Strength', muscleGroup: 'Legs', description: 'Attach a cable to your ankle and move your leg outward to target the gluteus medius.' },
  { name: 'Clamshells', category: 'Strength', muscleGroup: 'Legs', description: 'Lie on your side and open your knees like a clamshell with a resistance band for glute activation.' },
  { name: 'Banded Crab Walk', category: 'Strength', muscleGroup: 'Legs', description: 'Walk sideways with a resistance band around your knees to activate the gluteus medius.' },

  // ─── STRENGTH: LEGS — CALVES ────────────────────────────────────────
  { name: 'Standing Calf Raise', category: 'Strength', muscleGroup: 'Legs', description: 'Rise onto your toes on a standing calf raise machine to target the gastrocnemius.' },
  { name: 'Seated Calf Raise', category: 'Strength', muscleGroup: 'Legs', description: 'Rise onto your toes on a seated calf raise machine to target the soleus.' },
  { name: 'Donkey Calf Raise', category: 'Strength', muscleGroup: 'Legs', description: 'Rise onto your toes while bent forward at the hips for an intense calf stretch and contraction.' },
  { name: 'Single-Leg Calf Raise', category: 'Strength', muscleGroup: 'Legs', description: 'Rise onto one toe on a step for unilateral calf development and balance.' },

  // ─── STRENGTH: CORE ─────────────────────────────────────────────────
  { name: 'Front Plank', category: 'Strength', muscleGroup: 'Core', description: 'Hold a push-up position on your forearms, keeping your body in a straight line.' },
  { name: 'Side Plank', category: 'Strength', muscleGroup: 'Core', description: 'Hold a sideways position on one forearm and the side of your foot for oblique strength.' },
  { name: 'Reverse Plank', category: 'Strength', muscleGroup: 'Core', description: 'Hold a face-up position on your forearms and heels to engage the posterior core.' },
  { name: 'Standard Crunches', category: 'Strength', muscleGroup: 'Core', description: 'Lie on your back and lift your shoulders off the floor by contracting your abdominals.' },
  { name: 'Reverse Crunches', category: 'Strength', muscleGroup: 'Core', description: 'Lie on your back and curl your hips off the floor toward your chest to target lower abs.' },
  { name: 'Bicycle Crunches', category: 'Strength', muscleGroup: 'Core', description: 'Alternate bringing opposite elbow to knee in a pedaling motion for oblique activation.' },
  { name: 'Lying Leg Raises', category: 'Strength', muscleGroup: 'Core', description: 'Lie on your back and raise your legs to 90 degrees, lowering slowly without touching the floor.' },
  { name: 'Hanging Leg Raises', category: 'Strength', muscleGroup: 'Core', description: 'Hang from a bar and raise your legs to parallel or higher for advanced core work.' },
  { name: 'Hanging Knee Raises', category: 'Strength', muscleGroup: 'Core', description: 'Hang from a bar and raise your knees toward your chest for lower abdominal engagement.' },
  { name: 'Russian Twists', category: 'Strength', muscleGroup: 'Core', description: 'Sit with knees bent and rotate your torso side to side while holding a weight.' },
  { name: 'Ab Rollout', category: 'Strength', muscleGroup: 'Core', description: 'Roll an ab wheel forward from your knees, extending your body, then pull back to start.' },
  { name: 'Dead Bug', category: 'Strength', muscleGroup: 'Core', description: 'Lie on your back and extend opposite arm and leg alternately while keeping your back flat.' },
  { name: 'Bird Dog', category: 'Strength', muscleGroup: 'Core', description: 'Extend opposite arm and leg from a hands-and-knees position for core stability and balance.' },
  { name: 'Pallof Press', category: 'Strength', muscleGroup: 'Core', description: 'Press a cable handle away from your chest and hold to resist rotation for anti-core training.' },
  { name: 'Cable Woodchops', category: 'Strength', muscleGroup: 'Core', description: 'Pull a cable diagonally across your body to develop rotational core power.' },
  { name: 'Stability Ball Crunches', category: 'Strength', muscleGroup: 'Core', description: 'Perform crunches on a stability ball for increased range of motion and core engagement.' },
  { name: 'V-ups', category: 'Strength', muscleGroup: 'Core', description: 'Simultaneously lift your legs and torso from a lying position to form a V shape.' },
  { name: 'Flutter Kicks', category: 'Strength', muscleGroup: 'Core', description: 'Lie on your back and alternate kicking your legs up and down just above the floor.' },
  { name: 'Toe Touches', category: 'Strength', muscleGroup: 'Core', description: 'Lie on your back with legs vertical and reach your hands toward your toes for upper abs.' },
  { name: 'Cable Crunch', category: 'Strength', muscleGroup: 'Core', description: 'Kneel in front of a cable and crunch your torso downward to target the abdominals.' },

  // ─── STRENGTH: FOREARMS ─────────────────────────────────────────────
  { name: 'Barbell Wrist Curls', category: 'Strength', muscleGroup: 'Forearms', description: 'Rest your forearms on a bench and curl a barbell using only your wrists.' },
  { name: 'Barbell Reverse Wrist Curls', category: 'Strength', muscleGroup: 'Forearms', description: 'Rest your forearms on a bench and extend your wrists upward against barbell resistance.' },
  { name: "Farmer's Walk", category: 'Strength', muscleGroup: 'Forearms', description: 'Hold heavy dumbbells or kettlebells at your sides and walk with a tall, stable posture.' },
  { name: 'Plate Pinch Hold', category: 'Strength', muscleGroup: 'Forearms', description: 'Pinch two weight plates together with your fingers and hold for time to build grip strength.' },
  { name: 'Towel Hang', category: 'Strength', muscleGroup: 'Forearms', description: 'Drape a towel over a pull-up bar and hang from it to develop crushing grip strength.' },
  { name: 'Wrist Roller', category: 'Strength', muscleGroup: 'Forearms', description: 'Roll a weight up and down a rope attached to a handle by rotating your wrists.' },
  { name: 'Finger Extensions', category: 'Strength', muscleGroup: 'Forearms', description: 'Spread your fingers apart against a rubber band to strengthen the extensor muscles.' },

  // ─── CARDIO ──────────────────────────────────────────────────────────
  { name: 'Treadmill Running', category: 'Cardio', muscleGroup: 'Full Body', description: 'Run at a steady pace on a treadmill to improve cardiovascular endurance.' },
  { name: 'Outdoor Running', category: 'Cardio', muscleGroup: 'Full Body', description: 'Run outdoors on roads or trails for cardiovascular conditioning and fresh air.' },
  { name: 'Stationary Cycling', category: 'Cardio', muscleGroup: 'Legs', description: 'Pedal a stationary bike at moderate intensity for low-impact cardiovascular exercise.' },
  { name: 'Outdoor Cycling', category: 'Cardio', muscleGroup: 'Legs', description: 'Ride a bicycle outdoors for cardiovascular fitness and lower body endurance.' },
  { name: 'Rowing Machine', category: 'Cardio', muscleGroup: 'Full Body', description: 'Pull a rowing machine handle while pushing with your legs for full-body cardio.' },
  { name: 'Jump Rope', category: 'Cardio', muscleGroup: 'Full Body', description: 'Skip rope at a steady rhythm to build coordination and cardiovascular stamina.' },
  { name: 'Stair Climber', category: 'Cardio', muscleGroup: 'Legs', description: 'Step continuously on a stair climber machine to elevate your heart rate and work the legs.' },
  { name: 'Elliptical Trainer', category: 'Cardio', muscleGroup: 'Full Body', description: 'Use an elliptical machine for a low-impact, full-body cardiovascular workout.' },
  { name: 'Swimming', category: 'Cardio', muscleGroup: 'Full Body', description: 'Swim laps in a pool for a zero-impact, full-body cardiovascular exercise.' },
  { name: 'Battle Ropes', category: 'Cardio', muscleGroup: 'Full Body', description: 'Alternate slamming heavy ropes up and down for an intense full-body cardio session.' },
  { name: 'Shadow Boxing', category: 'Cardio', muscleGroup: 'Full Body', description: 'Throw punches at the air in combinations to improve cardio and coordination.' },
  { name: 'Dance Cardio', category: 'Cardio', muscleGroup: 'Full Body', description: 'Follow choreographed dance moves to upbeat music for a fun cardiovascular workout.' },
  { name: 'Kickboxing Cardio', category: 'Cardio', muscleGroup: 'Full Body', description: 'Perform kickboxing combinations without contact for a high-energy cardio session.' },
  { name: 'Sled Push', category: 'Cardio', muscleGroup: 'Legs', description: 'Push a weighted sled across the floor for cardiovascular conditioning and leg power.' },
  { name: 'Assault Bike', category: 'Cardio', muscleGroup: 'Full Body', description: 'Pedal and pump the handles of an air bike for scalable full-body cardio.' },
  { name: 'Cross-Country Skiing', category: 'Cardio', muscleGroup: 'Full Body', description: 'Simulate cross-country skiing on a machine for full-body endurance training.' },
  { name: 'Hiking', category: 'Cardio', muscleGroup: 'Full Body', description: 'Walk on natural terrain with elevation changes for low-intensity steady-state cardio.' },
  { name: 'Brisk Walking', category: 'Cardio', muscleGroup: 'Full Body', description: 'Walk at a fast pace to elevate your heart rate for accessible daily cardiovascular exercise.' },
  { name: 'Vigorous Yard Work', category: 'Cardio', muscleGroup: 'Full Body', description: 'Mow, rake, or dig with sustained effort for functional cardiovascular activity.' },
  { name: 'Active Recovery Walk', category: 'Cardio', muscleGroup: 'Full Body', description: 'Walk at a gentle pace on rest days to promote blood flow and recovery.' },

  // ─── FLEXIBILITY ─────────────────────────────────────────────────────
  { name: 'Downward Dog', category: 'Flexibility', muscleGroup: 'Full Body', description: 'Form an inverted V shape with your body to stretch the hamstrings, calves, and shoulders.' },
  { name: 'Warrior I Pose', category: 'Flexibility', muscleGroup: 'Legs', description: 'Step into a deep lunge with arms raised overhead to open the hips and stretch the chest.' },
  { name: 'Warrior II Pose', category: 'Flexibility', muscleGroup: 'Legs', description: 'Hold a wide lunge with arms extended to strengthen the legs while opening the hips.' },
  { name: 'Warrior III Pose', category: 'Flexibility', muscleGroup: 'Legs', description: 'Balance on one leg while extending the other leg and torso parallel to the floor.' },
  { name: 'Tree Pose', category: 'Flexibility', muscleGroup: 'Legs', description: 'Balance on one leg with the other foot on your inner thigh and hands overhead or at heart center.' },
  { name: 'Cobra Pose', category: 'Flexibility', muscleGroup: 'Core', description: 'Lie face-down and press your chest up while keeping hips on the floor to stretch the abs and chest.' },
  { name: "Child's Pose", category: 'Flexibility', muscleGroup: 'Back', description: 'Kneel and fold forward with arms extended to gently stretch the back and shoulders.' },
  { name: 'Hamstring Stretch', category: 'Flexibility', muscleGroup: 'Legs', description: 'Sit with one leg extended and reach toward your toes to lengthen the hamstring.' },
  { name: 'Quad Stretch', category: 'Flexibility', muscleGroup: 'Legs', description: 'Stand on one leg and pull your opposite heel toward your glute to stretch the quadriceps.' },
  { name: 'Hip Flexor Stretch', category: 'Flexibility', muscleGroup: 'Legs', description: 'Kneel in a lunge position and push your hips forward to stretch the hip flexors.' },
  { name: 'Pigeon Pose', category: 'Flexibility', muscleGroup: 'Legs', description: 'Fold one leg in front of you on the floor and extend the other behind to deeply stretch the glutes.' },
  { name: 'Cat-Cow Stretch', category: 'Flexibility', muscleGroup: 'Back', description: 'Alternate between arching and rounding your back on all fours to mobilize the spine.' },
  { name: 'Shoulder Cross-Body Stretch', category: 'Flexibility', muscleGroup: 'Shoulders', description: 'Pull one arm across your chest with the other hand to stretch the posterior shoulder.' },
  { name: 'Tricep Overhead Stretch', category: 'Flexibility', muscleGroup: 'Triceps', description: 'Reach one hand down your back and press the elbow with the other hand to stretch the triceps.' },
  { name: 'Doorway Chest Stretch', category: 'Flexibility', muscleGroup: 'Chest', description: 'Place your forearm on a door frame and lean forward to open and stretch the chest muscles.' },
  { name: 'Seated Spinal Twist', category: 'Flexibility', muscleGroup: 'Core', description: 'Sit and rotate your torso to one side, using your opposite hand on your knee for leverage.' },
  { name: 'Butterfly Stretch', category: 'Flexibility', muscleGroup: 'Legs', description: 'Sit with the soles of your feet together and press your knees down to stretch the inner thighs.' },
  { name: 'Standing Calf Stretch', category: 'Flexibility', muscleGroup: 'Legs', description: 'Step one foot back and press the heel into the floor to stretch the calf muscle.' },
  { name: 'Neck Rolls', category: 'Flexibility', muscleGroup: 'Shoulders', description: 'Slowly rotate your head in a circular motion to release tension in the neck and upper traps.' },
  { name: 'Piriformis Stretch', category: 'Flexibility', muscleGroup: 'Legs', description: 'Lie on your back and cross one ankle over the opposite knee, pulling toward your chest.' },

  // ─── HIIT ────────────────────────────────────────────────────────────
  { name: 'Burpees', category: 'HIIT', muscleGroup: 'Full Body', description: 'Drop to the floor, perform a push-up, jump your feet to your hands, and explode upward.' },
  { name: 'Mountain Climbers', category: 'HIIT', muscleGroup: 'Core', description: 'Start in a plank position and alternate driving your knees toward your chest rapidly.' },
  { name: 'Jump Squats', category: 'HIIT', muscleGroup: 'Legs', description: 'Squat down and explode upward into a jump, landing softly back into the squat position.' },
  { name: 'Plyo Push-ups', category: 'HIIT', muscleGroup: 'Chest', description: 'Perform a push-up explosively enough that your hands leave the ground at the top.' },
  { name: 'Box Jumps', category: 'HIIT', muscleGroup: 'Legs', description: 'Jump from the floor onto a raised box or platform, landing with soft knees.' },
  { name: 'Kettlebell Swings', category: 'HIIT', muscleGroup: 'Legs', description: 'Swing a kettlebell between your legs and thrust your hips to drive it to chest height.' },
  { name: 'Slam Ball', category: 'HIIT', muscleGroup: 'Core', description: 'Lift a medicine ball overhead and slam it into the ground with full-body force.' },
  { name: 'Tire Flips', category: 'HIIT', muscleGroup: 'Full Body', description: 'Lift and flip a heavy tire using your legs and hips for explosive full-body power.' },
  { name: 'Bear Crawls', category: 'HIIT', muscleGroup: 'Full Body', description: 'Crawl forward on hands and feet with knees hovering off the ground for total-body conditioning.' },
  { name: 'Lateral Bounds', category: 'HIIT', muscleGroup: 'Legs', description: 'Leap sideways from one foot to the other, covering maximum distance with each jump.' },
  { name: 'Tuck Jumps', category: 'HIIT', muscleGroup: 'Legs', description: 'Jump vertically and tuck your knees toward your chest at the peak of the jump.' },
  { name: 'Broad Jumps', category: 'HIIT', muscleGroup: 'Legs', description: 'Jump forward as far as possible from a standing position, landing softly on both feet.' },
  { name: 'Shuttle Runs', category: 'HIIT', muscleGroup: 'Full Body', description: 'Sprint back and forth between two points for short, repeated bursts of maximum effort.' },
  { name: 'Sprint Intervals', category: 'HIIT', muscleGroup: 'Full Body', description: 'Alternate between all-out sprints and brief recovery periods for maximum calorie burn.' },
  { name: 'Devil Press', category: 'HIIT', muscleGroup: 'Full Body', description: 'Perform a burpee with dumbbells, then swing them overhead in one explosive movement.' },
];
